-- Lesson seed, generated from the courses page's own COURSES array.
-- Regenerate with: node scripts/extract-lessons.js
-- Idempotent: re-running adds only lectures that are not already there.

insert into public.lessons (course_id, title, summary, content, duration, order_index)
select c.id, v.title, v.unit, v.unit || chr(46) || chr(32) || v.title, v.dur, v.idx
from (values
('CS102','What is C++ & how a program is structured','Introduction to C++ & Program Structure','14:20',0),
('CS102','int, double, char, bool & arithmetic operators','Data Types, Variables & Operators','18:05',1),
('CS102','string type, cin, getline & output formatting','Strings & Formatted I/O','15:40',2),
('CS102','Conditional logic & the switch statement','Decision Making (if / else if / switch / ternary)','20:12',3),
('CS102','while & for loops, building trace tables','Loops Part 1 (while, for, trace tables)','22:30',4),
('CS102','Nested loops, break & continue','Loops Part 2 (do-while, nested, break, continue, flags)','19:15',5),
('CS102','Writing & calling functions','Functions Part 1 (declaration, definition, call, void, return)','17:50',6),
('CS102','Scope, recursion & pass-by-reference','Functions Part 2 (scope, global/local, recursion, references)','24:00',7),
('CS102','Declaring & looping over 1D arrays','Arrays Part 1 (1D, indexing, algorithms, partially filled)','21:10',8),
('CS102','2D arrays & matrix operations','Arrays Part 2 (2D, matrices, arrays in functions, diagonal)','23:25',9),
('CS102','Addresses, dereferencing & pointer basics','Pointers (address, dereference, arrays & pointers, C-strings)','25:40',10),
('CS102','Reading from & writing to files','File Streams (ifstream, ofstream, fstream, persistent data)','18:30',11),
('CS102','Defining & using structs','Structures (struct — defining new types)','16:45',12),
('CS103','Binary, Octal, Hex, BCD, Gray Code','Numbering Systems','22:10',0),
('CS103','AND, OR, NOT, NAND, NOR, XOR, XNOR','Logic Gates & Truth Tables','18:30',1),
('CS103','12 identities, DeMorgan, Absorption, Consensus','Boolean Algebra','20:40',2),
('CS103','Minterms, Maxterms, ∑m, ∏M','Standard Forms (SOP & POS)','19:15',3),
('CS103','Gray code grid, grouping, wrap-around','3-Variable K-Maps','21:00',4),
('CS103','Group sizes 1/2/4/8/16, corner wraps, Don''t Care','4-Variable K-Maps & Don''t Cares','24:30',5),
('CS103','Half Adder, Full Adder, Ripple Carry, 2''s complement','Adders (Half, Full, Ripple Carry, Subtractor)','26:15',6),
('CS103','n-to-2^n decoder, Enable pin, 7-Segment, Priority encoder','Decoders & Encoders','22:45',7),
('CS103','MUX as universal logic, Full Adder with 4X1 MUX','Multiplexers & DeMultiplexers','20:30',8),
('MA103','ODE vs PDE, order, degree, linear vs nonlinear','Introduction & Classification','16:20',0),
('MA103','Separation of variables, initial conditions','Separable Differential Equations','19:40',1),
('MA103','Standard form, integrating factor','Linear First-Order ODEs','22:10',2),
('MA103','Exactness test, solution method, integrating factors','Exact Differential Equations','21:30',3),
('MA103','Type 1 (depends on x), Type 2 (depends on y)','Non-Exact DEs & Integrating Factors','23:15',4),
('MA103','Test, v = y/x substitution, back-substitution','Homogeneous First-Order DEs','20:45',5),
('MA103','Characteristic equation, distinct/repeated/complex roots','Higher-Order Homogeneous Linear DEs','25:30',6),
('MA103','Guessing table, duplication rule','Non-Homogeneous DEs: Undetermined Coefficients','24:00',7),
('MA104','Random experiments, sample space, events, axioms','Probability Theory Foundations','18:20',0),
('MA104','nPr, nCr, factorial, identical items, repetition','Counting Rules (Permutations & Combinations)','20:40',1),
('MA104','P(A|B), multiplication rule, total probability, Bayes','Conditional Probability & Bayes'' Theorem','24:10',2),
('MA104','PMF, CDF, expected value, variance','Discrete Random Variables & PMF','22:15',3),
('MA104','PDF, CDF, probability as integral','Continuous Random Variables & PDF','21:30',4),
('MA104','E(X), E(g(X)), variance, linearity properties','Mathematical Expectation','19:45',5),
('MA104','Binomial PMF, mean, variance; Geometric','Binomial & Geometric Distributions','23:20',6),
('MA104','Poisson, Uniform(a,b), Normal Z-score, Exponential','Poisson, Uniform, Normal & Exponential','26:00',7),
('MA101','Definition, one-sided, continuity, IVT','Limits & Continuity','20:00',0),
('MA101','Definition, rules, implicit differentiation','Derivatives (Power, Product, Quotient, Chain)','24:30',1),
('MA101','Min/max, concavity, optimization, L''Hôpital','Applications of Derivatives','22:45',2),
('MA101','Antiderivatives, FTC, substitution','Integration (Indefinite & Definite)','23:10',3),
('MA101','Integration by parts, trig substitution, partial fractions','Techniques of Integration','28:00',4),
('MA101','Area between curves, volume (disk method), arc length','Applications of Integrals','25:15',5),
('PH101','1D/2D motion, projectile, relative motion','Mechanics: Kinematics','22:00',0),
('PH101','F=ma, friction, circular motion','Mechanics: Dynamics (Newton''s Laws)','24:30',1),
('PH101','Work-energy theorem, conservation of energy, power','Work, Energy & Power','21:15',2),
('PH101','Coulomb''s Law, electric field, Gauss''s Law','Electricity: Coulomb''s Law & Electric Fields','23:40',3),
('PH101','V=IR, KVL, KCL, series/parallel','Circuits: Ohm''s Law, Kirchhoff''s Laws','20:50',4),
('PH101','Magnetic force, Faraday''s Law, Lenz''s Law','Magnetism & Lenz''s Law','22:30',5),
('MA102','Logical operators, truth tables, equivalences, tautologies','Propositional Logic','20:00',0),
('MA102','Quantifiers, negation, inference rules, induction','Predicate Logic & Proofs','22:30',1),
('MA102','Sets, subsets, operations, cardinality, power sets','Set Theory','18:45',2),
('MA102','Permutations, combinations, binomial theorem, pigeonhole','Combinatorics','21:10',3),
('MA102','Functions, injective/surjective/bijective, relations','Functions & Relations','19:30',4),
('CS101','Binary, Octal, Hex, BCD, Gray Code, complements','Number Systems & Binary Arithmetic','22:00',0),
('CS101','Von Neumann architecture, CPU, RAM, ROM, BIOS','Basic Hardware (CPU, Memory, I/O, Motherboard)','20:30',1),
('CS101','System vs application software, OS functions, compilers','Basic Software (OS, Compilers, Interpreters)','18:45',2),
('CS101','Topologies, devices, OSI model, TCP/IP','Networking Fundamentals','24:10',3),
('CS101','IPv4, IPv6, subnetting, TCP vs UDP, DNS','IP Addressing & Protocols','21:50',4)
) as v(code,title,unit,dur,idx)
join public.courses c on c.code = v.code
where not exists (select 1 from public.lessons l where l.course_id = c.id and l.title = v.title);
