"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, Calculator, Check, Code2, Download, FunctionSquare, GitBranch, NotebookPen, Pause, Play, RotateCcw, Timer, X } from "lucide-react";
import { Markdown } from "./markdown";
import { downloadText } from "@/lib/moeai/workspace";
export type Tool = "calculator" | "graph" | "code" | "logic" | "notebook" | "focus";
export const toolItems = [
  { id: "calculator" as Tool, label: "Calculator", hint: "Evaluate & differentiate", icon: Calculator },
  { id: "graph" as Tool, label: "Graph plotter", hint: "See the function", icon: FunctionSquare },
  { id: "code" as Tool, label: "Code studio", hint: "Write, run, understand", icon: Code2 },
  { id: "logic" as Tool, label: "Truth table", hint: "Test Boolean expressions", icon: GitBranch },
  { id: "notebook" as Tool, label: "Notebook", hint: "Keep the important parts", icon: NotebookPen },
  { id: "focus" as Tool, label: "Focus timer", hint: "One thing at a time", icon: Timer },
];
export default function ToolPanel({ tool, onClose, onAsk, notebook, onNotebook }: { tool: Tool; onClose: () => void; onAsk: (text: string) => void; notebook: string; onNotebook: (text: string) => void }) {
  const info = toolItems.find(t => t.id === tool)!;
  return <aside className="mx-tool-panel" aria-label={info.label}><header><div><span className="mx-eyebrow">WORKBENCH</span><h2>{info.label}</h2></div><button className="mx-icon" aria-label="Close tool" onClick={onClose}><X size={18}/></button></header><div className="mx-tool-body">{tool === "calculator" || tool === "graph" || tool === "logic" ? <MathTool key={tool} type={tool} onAsk={onAsk}/> : tool === "code" ? <CodeStudio onAsk={onAsk}/> : tool === "focus" ? <FocusTimer/> : <Notebook text={notebook} onChange={onNotebook}/>}</div><footer><span className="mx-dot"/> Tools run on your device</footer></aside>;
}
function MathTool({type,onAsk}: {type: "calculator" | "graph" | "logic";onAsk:(text:string)=>void}) {
  const [input,setInput] = useState(type === "graph" ? "sin(x)" : type === "logic" ? "(A and B) or C" : "(2^8 - 1) / 5");
  const [result,setResult] = useState(""); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  const [points,setPoints] = useState<{x:number;y:number|null}[]>([]); const [rows,setRows] = useState<{A:boolean;B:boolean;C:boolean;value:boolean}[]>([]);
  async function run(derivative = false) { setError(""); setBusy(true); try { const math = await import("@/lib/moeai/math");
    if(type === "graph") { setPoints(math.graphPoints(input)); setResult(`y = ${input}`); }
    else if(type === "logic") { setRows(math.truthTable(input)); setResult(input); }
    else setResult(derivative ? math.differentiate(input) : math.calculate(input));
  } catch(e) { setError(e instanceof Error ? e.message : "Check the expression."); setResult(""); setPoints([]); setRows([]); } finally { setBusy(false); } }
  let path = ""; let connected = false; let previous = 0;
  for (const p of points) { if(p.y === null){connected=false;continue;} const y=150-p.y*14; path += `${connected && Math.abs(y-previous)<100 ? "L":"M"}${150+p.x*14},${y} `; connected=true;previous=y; }
  return <><p className="mx-muted">{type === "graph" ? "Plot a real-valued function. Use x as the variable." : type === "logic" ? "Use A, B, C with and, or, not, xor and parentheses." : "A deterministic calculator. Angles are in radians. Use x for derivatives."}</p><label className="mx-field">{type === "graph" ? "f(x)" : "Expression"}<input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")run();}} maxLength={300}/></label><div className="mx-inline"><button className="mx-primary" onClick={()=>run()} disabled={busy}>{busy ? "Calculating…" : type === "graph" ? "Plot function" : type === "logic" ? "Build truth table" : "Calculate"}</button>{type === "calculator" && <button className="mx-secondary" disabled={busy} onClick={()=>run(true)}>d/dx</button>}</div>{error && <p className="mx-error" role="alert">{error}</p>}{type === "graph" && <div className="mx-graph"><svg viewBox="0 0 300 300" role="img" aria-label={result || "Graph canvas from minus ten to ten"}><defs><pattern id="graph-grid" width="14" height="14" patternUnits="userSpaceOnUse"><path d="M 14 0 L 0 0 0 14" fill="none" stroke="currentColor" opacity=".1"/></pattern></defs><rect width="300" height="300" fill="url(#graph-grid)"/><path d="M10 150H290 M150 10V290" stroke="currentColor" opacity=".35"/><text x="275" y="168">x</text><text x="158" y="18">y</text><text x="8" y="166">−10</text><text x="276" y="146">10</text><path d={path} stroke="var(--mx-accent)" fill="none" strokeWidth="2.5"/></svg><small>Window: x ∈ [−10, 10], y ∈ [−10, 10]</small></div>}{rows.length>0 && <table className="mx-table"><thead><tr>{["A","B","C","Output"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{[r.A,r.B,r.C,r.value].map((v,j)=><td key={j} className={j===3&&v?"mx-one":""}>{Number(v)}</td>)}</tr>)}</tbody></table>}{result && <div className="mx-result"><span className="mx-eyebrow">RESULT</span><p>{result}</p><button className="mx-text-button" onClick={()=>onAsk(`Explain this ${type} result: ${input} → ${result}${rows.length ? "\n"+JSON.stringify(rows):""}`)}>Explain with Moe <ArrowUpRight size={14}/></button></div>}<div className="mx-tool-examples"><span className="mx-eyebrow">TRY AN EXPRESSION</span>{(type==="graph"?["x^2 / 5", "sin(x)", "cos(x) * x"]:type==="logic"?["A xor B", "not (A and B)", "(A and B) or C"]:["sqrt(144) + 2^3", "sin(pi / 2)", "x^3 + 2*x"]).map(ex=><button key={ex} onClick={()=>setInput(ex)}>{ex}<ArrowUpRight size={13}/></button>)}</div></>;
}
function CodeStudio({onAsk}:{onAsk:(text:string)=>void}) {
  const [language,setLanguage] = useState("javascript"); const [code,setCode] = useState('const numbers = [1, 2, 3, 4, 5];\nconst squares = numbers.map(n => n * n);\nconsole.log(squares);');
  const [output,setOutput] = useState(""); const [running,setRunning] = useState(false); const frame = useRef<HTMLIFrameElement>(null); const cleanup = useRef<()=>void>(()=>{});
  useEffect(()=>()=>cleanup.current(),[]);
  function run() {
    if(!frame.current || running)return; setRunning(true);setOutput(""); const token = crypto.randomUUID();
    const workerCode = `const console={log:(...args)=>postMessage(args.map(x=>typeof x==='string'?x:JSON.stringify(x)).join(' ')),error:(...args)=>postMessage(args.join(' ')),warn:(...args)=>postMessage(args.join(' '))};\ntry {\n${code}\n} catch(e) { postMessage('Error: '+e.message); }\npostMessage('__MOE_DONE__');`;
    const script = `const send=(value)=>parent.postMessage({token:${JSON.stringify(token)},output:value},'*');const worker=new Worker(URL.createObjectURL(new Blob([${JSON.stringify(workerCode).replace(/</g,"\\u003c")}],{type:'text/javascript'})));worker.onmessage=e=>send(e.data);worker.onerror=e=>send('Error: '+e.message);`;
    const onMessage=(event:MessageEvent)=>{if(event.source!==frame.current?.contentWindow||event.data?.token!==token)return; if(event.data.output === "__MOE_DONE__") {finish();return;} if(typeof event.data.output==="string")setOutput(previous=>(previous+event.data.output+"\n").slice(0,15000));};
    const timeout=setTimeout(()=>{setOutput(p=>p+"\nExecution stopped after 3 seconds.");finish();},3000);
    function finish(){clearTimeout(timeout);window.removeEventListener("message",onMessage);setRunning(false);if(frame.current)frame.current.srcdoc="";}
    cleanup.current=()=>{clearTimeout(timeout);window.removeEventListener("message",onMessage);};window.addEventListener("message",onMessage);
    frame.current.srcdoc=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' blob:; worker-src blob:; connect-src 'none'"><script>${script}<\/script>`;
  }
  return <><p className="mx-muted">Run JavaScript in an isolated browser sandbox. Use Moe to explain or debug C++, Python, and TypeScript.</p><label className="mx-field">Language<select value={language} onChange={e=>setLanguage(e.target.value)}>{["javascript","typescript","cpp","python"].map(l=><option key={l}>{l}</option>)}</select></label><textarea className="mx-code-editor" aria-label="Code editor" spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} maxLength={20000}/><div className="mx-inline">{language === "javascript" && <button className="mx-primary" onClick={run} disabled={running}><Play size={14}/>{running?"Running…":"Run code"}</button>}<button className="mx-secondary" onClick={()=>onAsk(`Help me understand and debug this code. Do not claim you ran it.\n\n\`\`\`${language}\n${code}\n\`\`\``)}>Ask Moe</button><button className="mx-icon" aria-label="Download code" onClick={()=>downloadText(`code.${language==="javascript"?"js":language==="python"?"py":language==="typescript"?"ts":"cpp"}`,code,"text/plain")}><Download size={16}/></button></div><div className="mx-console"><span className="mx-eyebrow">CONSOLE</span><pre>{output || "Output appears here when you run JavaScript."}</pre></div><iframe ref={frame} sandbox="allow-scripts" title="Isolated JavaScript runtime" hidden/></>;
}
function Notebook({text,onChange}:{text:string;onChange:(text:string)=>void}) { const [preview,setPreview]=useState(false); return <><div className="mx-inline"><button className="mx-secondary" onClick={()=>setPreview(!preview)}>{preview?"Edit notes":"Preview Markdown"}</button><button className="mx-icon" aria-label="Export notebook" onClick={()=>downloadText("moeai-notebook.md",text)}><Download size={16}/></button></div>{preview?<Markdown text={text || "*Your notebook is empty.*"}/>:<textarea className="mx-notebook" aria-label="Notebook" value={text} onChange={e=>onChange(e.target.value)} placeholder={"# Things that clicked\n\nSave explanations from chat, or write your own notes.\n\nMath works here too: $E = mc^2$"} maxLength={50000}/>}<p className="mx-muted"><Check size={12}/> Saved on this device</p></>; }
function FocusTimer() {
  const [minutes,setMinutes]=useState(25); const [left,setLeft]=useState(25*60); const [end,setEnd]=useState<number|null>(null);
  useEffect(()=>{if(!end)return;const tick=()=>{const next=Math.max(0,Math.ceil((end-Date.now())/1000));setLeft(next);if(!next)setEnd(null);};const id=setInterval(tick,250);return()=>clearInterval(id);},[end]);
  return <div className="mx-focus"><div className="mx-focus-orbit"><Timer size={26}/><strong>{String(Math.floor(left/60)).padStart(2,"0")}<span>:</span>{String(left%60).padStart(2,"0")}</strong><p>{left===0?"Done. Take a breath.":end?"Just this one thing.":"A little focus goes a long way."}</p></div><div className="mx-inline">{[5,15,25,50].map(m=><button key={m} className={m===minutes?"mx-primary":"mx-secondary"} onClick={()=>{setMinutes(m);setLeft(m*60);setEnd(null);}}>{m}m</button>)}</div><div className="mx-inline"><button className="mx-primary" onClick={()=>setEnd(end?null:Date.now()+Math.max(1,left)*1000)}>{end?<Pause size={16}/>:<Play size={16}/>} {end?"Pause":"Start focus"}</button><button className="mx-icon" aria-label="Reset timer" onClick={()=>{setEnd(null);setLeft(minutes*60);}}><RotateCcw size={16}/></button></div><p className="mx-muted">Keep this panel open during your session.</p></div>;
}
