"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@heroui/react";
import { ArrowDown, ArrowLeft, ArrowUp, ArrowUpRight, Bell, BookOpen, Check, ChevronDown, Code2, Copy, Download, FileText, GraduationCap, Library, Menu, MessageSquare, NotebookPen, PanelLeftClose, Paperclip, Plus, Search, Settings2, SlidersHorizontal, Sparkles, Square, Volume2, Wrench, X, CalendarDays, RotateCcw } from "lucide-react";
import { Markdown } from "./markdown";
import { LibraryView } from "./library";
import { Planner } from "./planner";
import { toolItems, type Tool } from "./tools";
import { defaults, downloadText, emptyWorkspace, loadWorkspace, modes, sourceExcerpt, starterFiles, storageKey, type Chat, type LibraryFile, type Message, type Mode, type Workspace as WorkspaceData } from "@/lib/moeai/workspace";
import { readLocalAttempts, summarize } from "@/lib/learning";
const ToolPanel = dynamic(()=>import("./tools"), { loading:()=> <aside className="mx-tool-panel mx-loading">Opening workbench…</aside> });
type View = "chat" | "library" | "planner";
const emptyMessages: Message[] = [];
export default function Workspace() {
  const [data,setData]=useState<WorkspaceData>(emptyWorkspace),[ready,setReady]=useState(false),[active,setActive]=useState<string|null>(null),[view,setView]=useState<View>("chat"),[mode,setMode]=useState<Mode>("tutor");
  const [input,setInput]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[tool,setTool]=useState<Tool|null>(null),[sidebar,setSidebar]=useState(false),[search,setSearch]=useState("");
  const [toast,setToast]=useState(""),[settingsOpen,setSettingsOpen]=useState(false),[menu,setMenu]=useState(false),[modeOpen,setModeOpen]=useState(false),[importing,setImporting]=useState(false),[now,setNow]=useState(0);
  const abort=useRef<AbortController|null>(null),textarea=useRef<HTMLTextAreaElement>(null),thread=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),stick=useRef(true),sending=useRef(false);
  const chat=data.chats.find(c=>c.id===active), messages=chat?.messages || emptyMessages, files=[...starterFiles,...data.files];
  const notify=useCallback((text:string)=>setToast(text),[]);
  useEffect(()=>{const id=requestAnimationFrame(()=>{setData(loadWorkspace());setReady(true);setNow(Date.now());});const timer=setInterval(()=>setNow(Date.now()),60000);return()=>{cancelAnimationFrame(id);clearInterval(timer);abort.current?.abort();};},[]);
  useEffect(()=>{if(!ready)return;const id=setTimeout(()=>{try{localStorage.setItem(storageKey,JSON.stringify(data));}catch{notify("Device storage is full. Export your chats or remove older files to save changes.");}},500);return()=>clearTimeout(id);},[data,ready,notify]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),5000);return()=>clearTimeout(id);},[toast]);
  useEffect(()=>{if(stick.current)thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:"smooth"});},[messages,busy]);
  useEffect(()=>{if(textarea.current){textarea.current.style.height="auto";textarea.current.style.height=`${Math.min(textarea.current.scrollHeight,180)}px`;}},[input]);
  useEffect(()=>{if(settingsOpen)dialog.current?.showModal();else dialog.current?.close();},[settingsOpen]);
  const newChat=useCallback(()=>{if(sending.current)return;setActive(null);setView("chat");setInput("");setSidebar(false);setSelected([]);setMode("tutor");stick.current=true;},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSidebar(true);document.getElementById("mx-chat-search")?.focus();}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==="o"){e.preventDefault();newChat();}if(e.key==="Escape"){setModeOpen(false);setMenu(false);setSidebar(false);}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[newChat]);
  function updateChat(id:string,update:(chat:Chat)=>Chat){setData(previous=>({...previous,chats:previous.chats.map(c=>c.id===id?update(c):c)}));}
  function selectSource(id:string){setSelected(previous=>{if(previous.includes(id))return previous.filter(x=>x!==id);if(previous.length>=3){notify("Choose up to 3 sources for a focused conversation.");return previous;}return [...previous,id];});}
  async function send(text=input, retry=false) {
    if(sending.current||!text.trim())return;
    if(text.trim().length>6000){notify("Keep each message under 6,000 characters. Add longer material to your library.");return;}
    if(mode==="library"&&!selected.length){setView("library");notify("Select a source, then ask Moe about it.");return;}
    sending.current=true;setBusy(true);setView("chat");setInput("");stick.current=true;
    const id=active||crypto.randomUUID(), assistantId=crypto.randomUUID();
    const history=retry?messages.slice(0,-1):messages;
    const userMessage:Message={id:crypto.randomUUID(),role:"user",content:text.trim(),sources:selected.map(id=>files.find(f=>f.id===id)?.title||"")};
    const pending=retry?history:[...history,userMessage];
    const draft:Chat={id,title:chat?.title||text.trim().slice(0,55),mode,updated:Date.now(),messages:[...pending,{id:assistantId,role:"assistant",content:""}]};
    setActive(id);setData(previous=>({...previous,chats:[draft,...previous.chats.filter(c=>c.id!==id)].slice(0,40)}));
    const controller=new AbortController();abort.current=controller;
    const timeout=setTimeout(()=>controller.abort("timeout"),55000);
    try {
      const response=await fetch("/api/moeai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stream:true,messages:pending.filter(m=>!m.status&&m.content).slice(-12).map(m=>({role:m.role,content:m.content.slice(-5000)})),context:{mode,profile:data.settings,sources:files.filter(f=>selected.includes(f.id)).map(f=>({id:f.id,title:f.title,content:sourceExcerpt(f.content,text,6000)}))}}),signal:controller.signal});
      if(!response.ok){const result=await response.json();throw new Error(result.error||"Moe couldn’t answer. Try again.");}
      if(!response.body)throw new Error("No response received. Please retry.");
      const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="",answer="",complete=false;
      try{while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.error)throw new Error(event.error);if(event.done)complete=true;if(typeof event.delta==="string"){answer+=event.delta;const content=answer;updateChat(id,c=>({...c,messages:c.messages.map(m=>m.id===assistantId?{...m,content}:m)}));}}}if(!complete||!answer)throw new Error("The response ended early. Please retry.");}finally{await reader.cancel().catch(()=>{});}
    }catch(error){const stopped=controller.signal.aborted&&controller.signal.reason!=="timeout";updateChat(id,c=>({...c,messages:c.messages.map(m=>m.id===assistantId?{...m,content:m.content|| (stopped?"Response stopped.":controller.signal.reason==="timeout"?"That took too long. Try again in a moment.":error instanceof Error?error.message:"Connection interrupted. Please retry."),status:stopped?"stopped":"error"}:m)}));}
    finally{clearTimeout(timeout);setBusy(false);sending.current=false;abort.current=null;textarea.current?.focus();}
  }
  function ask(text:string){setInput(text);setView("chat");setTimeout(()=>textarea.current?.focus(),0);}
  async function importFiles(list:FileList) {
    if(importing)return;setImporting(true);const added:LibraryFile[]=[];
    try {for(const file of Array.from(list).slice(0,5)){
      if(file.size>8*1024*1024)throw new Error(`${file.name}: keep files under 8 MB.`);
      let content="";
      if(file.name.toLowerCase().endsWith(".pdf")){
        const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="/vendor/pdf.worker.min.mjs";
        const loading=pdfjs.getDocument({data:await file.arrayBuffer()});const document=await loading.promise;
        try {for(let page=1;page<=Math.min(document.numPages,40);page++){const text=await(await document.getPage(page)).getTextContent();content+=`\n\nPage ${page}\n`+text.items.map(item=>"str" in item?item.str:"").join(" ");}if(!content.replace(/Page \d+/g,"").trim())throw new Error("This PDF is scanned. Text extraction needs a text-based PDF.");if(document.numPages>40)content+="\n[Only the first 40 pages were imported.]";}finally{await loading.destroy();}
      } else if(/\.(md|txt|csv|json|cpp|py|js|ts)$/i.test(file.name))content=await file.text();else throw new Error("Use a PDF, Markdown, text, CSV, JSON, or code file.");
      if(!content.trim())throw new Error(`${file.name} contains no readable text.`);
      added.push({id:crypto.randomUUID(),title:file.name,content:content.slice(0,150000),scope:"student",course:"Personal upload",added:Date.now()});
    }
    if(data.files.length+added.length>40||[...data.files,...added].reduce((n,f)=>n+f.content.length,0)>700000)throw new Error("Your device library is full. Remove older material before importing more.");
    setData(p=>({...p,files:[...added,...p.files]}));setSelected(p=>[...new Set([...p,...added.map(f=>f.id)])].slice(0,3));notify(`${added.length} material${added.length!==1?"s":""} added and ready to use.`);
    }catch(e){notify(e instanceof Error?e.message:"Could not read the file.");}finally{setImporting(false);}
  }
  const upcoming=data.events.filter(e=>!e.done&&Date.parse(e.date)>=now&&Date.parse(e.date)-now<3*86400000&&!data.dismissed.includes(e.id)).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date))[0];
  const stats=ready?summarize(readLocalAttempts()):null;
  const weakness=stats?.weaknesses[0];
  const suggestion=upcoming?{id:upcoming.id,text:`${upcoming.title} is ${Math.ceil((Date.parse(upcoming.date)-now)/3600000)<24?"less than a day away":"coming up"}. Let’s make a plan.`,prompt:`Help me prepare for ${upcoming.title} on ${new Date(upcoming.date).toLocaleString()}. Ask me what I need to cover.`}:weakness?{id:`weak-${weakness.topic}`,text:`${weakness.topic} could use a little practice. Want a quick challenge?`,prompt:`Give me a short practice question on ${weakness.topic}. Wait for my answer.`}:null;
  const filteredChats=data.chats.filter(c=>`${c.title} ${c.messages.map(m=>m.content).join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  return <div className={`mx-app ${tool?"has-tool":""}`} data-moe-theme={data.settings.theme}>
    <div className="mx-ambient" aria-hidden="true"/><aside className={`mx-sidebar ${sidebar?"open":""}`}><Link className="mx-brand" href="/"><Image src="/brand/moeai-logo.jpg" alt="MoeAI logo" width={44} height={44}/><span>Moe<span>AI</span><small>by EduMoe</small></span></Link><button className="mx-mobile-close mx-icon" onClick={()=>setSidebar(false)} aria-label="Close navigation"><PanelLeftClose size={18}/></button>
      <Button className="mx-new-chat" onPress={newChat} isDisabled={busy}><Plus size={17}/> New conversation <span>⌘ O</span></Button>
      <label className="mx-search mx-sidebar-search"><Search size={15}/><input id="mx-chat-search" placeholder="Search conversations" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></label>
      <nav className="mx-nav" aria-label="Workspace"><button className={view==="chat"?"active":""} onClick={()=>{setView("chat");setSidebar(false);}}><MessageSquare size={17}/> Conversations</button><button className={view==="library"?"active":""} onClick={()=>{setView("library");setSidebar(false);}}><Library size={17}/> Library <span>{files.length}</span></button><button className={view==="planner"?"active":""} onClick={()=>{setView("planner");setSidebar(false);}}><CalendarDays size={17}/> Study plan {data.events.some(e=>!e.done)&&<i/>}</button></nav>
      <div className="mx-history-heading"><span className="mx-eyebrow">YOUR CONVERSATIONS</span><span>{data.chats.length}</span></div><div className="mx-history">{filteredChats.length?filteredChats.map(c=><div key={c.id} className={`mx-history-item ${c.id===active&&view==="chat"?"active":""}`}><button disabled={busy} onClick={()=>{setActive(c.id);setMode(c.mode);setView("chat");setSidebar(false);setSelected([]);stick.current=true;}}><MessageSquare size={14}/><span>{c.title}</span></button><button className="mx-history-delete" aria-label={`Delete conversation ${c.title}`} disabled={busy} onClick={()=>{setData(p=>({...p,chats:p.chats.filter(x=>x.id!==c.id)}));if(active===c.id)setActive(null);}}><X size={12}/></button></div>):<p className="mx-history-empty">{search?"No matching conversations.":"Good conversations start with a question. Yours will live here."}</p>}</div>
      <div className="mx-sidebar-bottom"><Link href="/" className="mx-back"><ArrowLeft size={14}/> Back to EduMoe <ArrowUpRight size={13}/></Link><button className="mx-profile" onClick={()=>setSettingsOpen(true)}><span className="mx-avatar">{data.settings.name?.[0]?.toUpperCase()||"Y"}</span><span><strong>{data.settings.name||"Your workspace"}</strong><small>Personal · saved on this device</small></span><Settings2 size={16}/></button></div>
    </aside>{sidebar&&<button className="mx-sidebar-scrim" aria-label="Close sidebar" onClick={()=>setSidebar(false)}/>}
    <main className="mx-main"><header className="mx-header"><div className="mx-header-left"><button className="mx-icon mx-menu-toggle" onClick={()=>setSidebar(true)} aria-label="Open navigation"><Menu size={20}/></button><span className="mx-header-breadcrumb">Workspace <span>/</span></span><strong>{view==="chat"?"MoeAI":view==="library"?"Library":"Study plan"}</strong><span className="mx-beta">BETA</span></div><div className="mx-header-actions"><span className="mx-live"><i/> Live AI</span><button className={`mx-icon ${tool?"selected":""}`} onClick={()=>setTool(tool?null:"calculator")} aria-label="Toggle workbench"><Wrench size={17}/></button><button className="mx-icon" aria-label="Workspace settings" onClick={()=>setSettingsOpen(true)}><SlidersHorizontal size={17}/></button></div></header>
      <div className="mx-main-body">{view==="library"?<LibraryView files={files} selected={selected} onSelect={selectSource} importing={importing} onImport={importFiles} onDelete={id=>{setData(p=>({...p,files:p.files.filter(f=>f.id!==id)}));setSelected(p=>p.filter(s=>s!==id));}} onStudy={()=>{setMode("library");setView("chat");setInput("Help me understand the key ideas in my selected sources.");}}/>:view==="planner"?<Planner events={data.events} onChange={events=>setData(p=>({...p,events}))} onAsk={ask}/>:<>
        <div className="mx-thread" ref={thread} onScroll={()=>{const el=thread.current;if(el)stick.current=el.scrollHeight-el.scrollTop-el.clientHeight<120;}}>
          {!messages.length?<div className="mx-welcome"><div className="mx-welcome-wordmark"><Image src="/brand/moeai-logo.jpg" alt="" width={86} height={86} priority/><span>YOUR MIND, WITH A LITTLE MORE ROOM.</span></div><h1>Let’s make it <em>click.</em></h1><p className="mx-welcome-copy">The messy question. The impossible chapter.<br/>The code that almost works. Start anywhere.</p>
            <div className="mx-starters">{[{icon:GraduationCap,title:"Understand something",text:"Explain a concept to me. First ask what I’m studying and where I’m stuck."},{icon:Code2,title:"Untangle some code",text:"Help me debug my code. Ask me to paste it and describe the problem."},{icon:BookOpen,title:"Study my material",text:"library"}].map(s=><button key={s.title} onClick={()=>s.text==="library"?setView("library"):ask(s.text)}><s.icon size={19}/><span>{s.title}</span><ArrowUpRight size={15}/></button>)}</div>
            {data.settings.proactive&&suggestion&&!data.dismissed.includes(suggestion.id)&&<div className="mx-nudge"><span className="mx-nudge-symbol"><Bell size={17}/></span><div><small>A NOTE FROM MOE</small><p>{suggestion.text}</p></div><button onClick={()=>ask(suggestion.prompt)} className="mx-icon" aria-label="Start suggested study session"><ArrowUpRight size={18}/></button><button className="mx-icon" aria-label="Dismiss suggestion" onClick={()=>setData(p=>({...p,dismissed:[...p.dismissed,suggestion.id]}))}><X size={14}/></button></div>}
            <div className="mx-workbench-strip"><span className="mx-eyebrow">THINK WITH TOOLS</span><div>{toolItems.slice(0,4).map(t=><button key={t.id} onClick={()=>setTool(t.id)}><t.icon size={15}/>{t.label}</button>)}</div></div>
          </div>:<div className="mx-messages"><div className="mx-conversation-title"><h1>{chat?.title}</h1><button className="mx-icon" aria-label="Export conversation" onClick={()=>downloadText(`${chat?.title||"conversation"}.md`,messages.map(m=>`## ${m.role==="user"?"You":"Moe"}\n\n${m.content}`).join("\n\n---\n\n"))}><Download size={16}/></button></div>{messages.map((message,index)=><article className={`mx-message ${message.role} ${message.status||""}`} key={message.id}><div className="mx-message-avatar">{message.role==="assistant"?<Image src="/brand/moeai-logo.jpg" alt="Moe" width={30} height={30}/>:<span>{data.settings.name?.[0]?.toUpperCase()||"Y"}</span>}</div><div className="mx-message-body"><div className="mx-message-author">{message.role==="assistant"?"Moe":data.settings.name||"You"}{message.role==="assistant"&&<span>AI</span>}</div>{!message.content?<div className="mx-thinking" role="status"><span/><span/><span/><small>Working through it…</small></div>:message.role==="assistant"?<Markdown text={message.content}/>:<p className="mx-user-text" dir="auto">{message.content}</p>}{message.sources?.length? <div className="mx-message-sources">{message.sources.map(s=><span key={s}><FileText size={12}/>{s}</span>)}</div>:null}{message.role==="assistant"&&message.content&&<div className="mx-message-actions"><button aria-label="Copy response" onClick={async()=>{try{await navigator.clipboard.writeText(message.content);notify("Response copied.");}catch{notify("Clipboard unavailable. Select and copy the text.");}}}><Copy size={14}/></button><button aria-label="Save response to notebook" onClick={()=>{setData(p=>({...p,notebook:(p.notebook+`\n\n## ${chat?.title}\n\n${message.content}`).slice(-50000)}));notify("Saved to your notebook.");}}><NotebookPen size={14}/></button><button aria-label="Read response aloud" onClick={()=>{if(!("speechSynthesis" in window)){notify("Read aloud is unavailable in this browser.");return;}speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(message.content.replace(/[*#`]/g,"")));}}><Volume2 size={14}/></button>{index===messages.length-1&&<button disabled={busy} aria-label="Retry response" onClick={()=>send(messages.filter(m=>m.role==="user").at(-1)?.content||"",true)}><RotateCcw size={14}/></button>}{message.status&&<span>{message.status==="error"?"Couldn’t connect · retry":"Stopped"}</span>}</div>}</div></article>)}{!busy&&messages.at(-1)?.role==="assistant"&&!messages.at(-1)?.status&&<div className="mx-followups">{["Try another explanation", "Give me an example", "Quiz me on this"].map(t=><button key={t} onClick={()=>send(t)}>{t}<ArrowUpRight size={12}/></button>)}</div>}</div>}
        </div>
        <div className="mx-composer-area"><div className="mx-selected-sources">{selected.map(id=>files.find(f=>f.id===id)).filter((f):f is LibraryFile=>Boolean(f)).map(f=><span key={f.id}><FileText size={13}/>{f.title}<button aria-label={`Remove source ${f.title}`} onClick={()=>selectSource(f.id)}><X size={12}/></button></span>)}</div><form className="mx-composer" onSubmit={e=>{e.preventDefault();send();}}><textarea ref={textarea} aria-label="Message Moe" placeholder={mode==="library"?"Ask something about your sources…":"What’s on your mind?"} value={input} onChange={e=>setInput(e.target.value)} maxLength={6000} rows={1} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><div className="mx-composer-bottom"><div className="mx-composer-controls"><button type="button" className="mx-icon" aria-label="Attach source material" disabled={importing} onClick={()=>fileInput.current?.click()}><Paperclip size={18}/></button><div className="mx-mode-picker"><button type="button" className="mx-mode-trigger" onClick={()=>{setModeOpen(!modeOpen);setMenu(false);}} aria-expanded={modeOpen}><Sparkles size={14}/>{modes.find(m=>m.id===mode)?.label}<ChevronDown size={12}/></button>{modeOpen&&<div className="mx-popover mx-modes">{modes.map(m=><button key={m.id} type="button" onClick={()=>{setMode(m.id);if(active)updateChat(active,c=>({...c,mode:m.id}));setModeOpen(false);}}><div><strong>{m.label}</strong><span>{m.description}</span></div>{mode===m.id&&<Check size={15}/>}</button>)}</div>}</div><div className="mx-tools-picker"><button type="button" className="mx-icon" aria-label="Choose a tool" aria-expanded={menu} onClick={()=>{setMenu(!menu);setModeOpen(false);}}><Plus size={17}/></button>{menu&&<div className="mx-popover">{toolItems.map(t=><button key={t.id} type="button" onClick={()=>{setTool(t.id);setMenu(false);}}><t.icon size={16}/>{t.label}</button>)}<button type="button" onClick={()=>{setView("library");setMenu(false);}}><Library size={16}/>Choose sources</button></div>}</div></div><div className="mx-composer-right"><span>{input.length>5000?`${input.length}/6000`:"↵ to send"}</span>{busy?<Button className="mx-send" isIconOnly aria-label="Stop response" onPress={()=>abort.current?.abort()}><Square size={15}/></Button>:<Button className="mx-send" isIconOnly type="submit" aria-label="Send message" isDisabled={!input.trim()||!ready}><ArrowUp size={19}/></Button>}</div></div></form><div className="mx-composer-footnote"><span>Moe can make mistakes. Stay curious. Check the important stuff.</span><button onClick={()=>thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:"smooth"})} aria-label="Scroll to latest message"><ArrowDown size={12}/></button></div></div>
      </>}</div>
    </main>{tool&&<ToolPanel tool={tool} onClose={()=>setTool(null)} onAsk={ask} notebook={data.notebook} onNotebook={notebook=>setData(p=>({...p,notebook}))}/>}
    <input ref={fileInput} hidden type="file" multiple accept=".pdf,.md,.txt,.csv,.json,.cpp,.py,.js,.ts" onChange={e=>{if(e.target.files)importFiles(e.target.files);e.target.value="";}}/>
    <dialog ref={dialog} className="mx-settings" onCancel={()=>setSettingsOpen(false)}><header><div><span className="mx-eyebrow">MAKE IT YOURS</span><h2>Your workspace, your way.</h2></div><button className="mx-icon" aria-label="Close settings" onClick={()=>setSettingsOpen(false)}><X size={18}/></button></header><label className="mx-field">What should Moe call you?<input value={data.settings.name} maxLength={80} onChange={e=>setData(p=>({...p,settings:{...p.settings,name:e.target.value}}))} placeholder="Your name"/></label><div className="mx-settings-grid"><label className="mx-field">Language<select value={data.settings.language} onChange={e=>setData(p=>({...p,settings:{...p.settings,language:e.target.value}}))}>{["Auto · match me","English","Egyptian Arabic","Franco-Arabic"].map(x=><option key={x}>{x}</option>)}</select></label><label className="mx-field">Answer style<select value={data.settings.detail} onChange={e=>setData(p=>({...p,settings:{...p.settings,detail:e.target.value}}))}>{["Balanced","Short and direct","Detailed with examples"].map(x=><option key={x}>{x}</option>)}</select></label></div><label className="mx-field">Things Moe should remember<textarea value={data.settings.memory} maxLength={2000} onChange={e=>setData(p=>({...p,settings:{...p.settings,memory:e.target.value}}))} placeholder="Your courses, learning goals, or how you like to study…"/></label><label className="mx-switch"><div><strong>Proactive study notes</strong><small>Upcoming deadlines and practice suggestions, inside the app.</small></div><input type="checkbox" checked={data.settings.proactive} onChange={e=>setData(p=>({...p,settings:{...p.settings,proactive:e.target.checked}}))}/></label><span className="mx-eyebrow">WORKSPACE ACCENT</span><div className="mx-themes">{["ruby","violet","ocean","amber"].map(theme=><button key={theme} aria-label={`${theme} theme`} aria-pressed={data.settings.theme===theme} data-color={theme} onClick={()=>setData(p=>({...p,settings:{...p.settings,theme}}))}>{data.settings.theme===theme&&<Check size={15}/>}</button>)}</div><p className="mx-muted">Chats, notes, files, and preferences are saved in this browser. Export a backup before switching devices. Your selected context is sent to the AI provider with each message.</p><div className="mx-inline"><button className="mx-secondary" onClick={()=>downloadText("moeai-workspace.json",JSON.stringify(data,null,2),"application/json")}><Download size={14}/>Export workspace</button><button className="mx-text-button" onClick={()=>setData(p=>({...p,settings:{...defaults}}))}>Reset preferences</button></div></dialog>
    {toast&&<div className="mx-toast" role="status"><Check size={16}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast("")}><X size={14}/></button></div>}
  </div>;
}
