export const LANGUAGE_META = {
  en: { nativeName: 'English', flag: 'en', names: { en:'English', ar:'الإنجليزية', es:'inglés', fr:'anglais', de:'Englisch', zh:'英语', hi:'अंग्रेज़ी' } },
  ar: { nativeName: 'العربية', flag: 'ar', names: { en:'Arabic', ar:'العربية', es:'árabe', fr:'arabe', de:'Arabisch', zh:'阿拉伯语', hi:'अरबी' } },
  es: { nativeName: 'Español', flag: 'es', names: { en:'Spanish', ar:'الإسبانية', es:'español', fr:'espagnol', de:'Spanisch', zh:'西班牙语', hi:'स्पेनिश' } },
  fr: { nativeName: 'Français', flag: 'fr', names: { en:'French', ar:'الفرنسية', es:'francés', fr:'français', de:'Französisch', zh:'法语', hi:'फ़्रेंच' } },
  de: { nativeName: 'Deutsch', flag: 'de', names: { en:'German', ar:'الألمانية', es:'alemán', fr:'allemand', de:'Deutsch', zh:'德语', hi:'जर्मन' } },
  zh: { nativeName: '简体中文', flag: 'zh', names: { en:'Simplified Chinese', ar:'الصينية المبسطة', es:'chino simplificado', fr:'chinois simplifié', de:'Vereinfachtes Chinesisch', zh:'简体中文', hi:'सरलीकृत चीनी' } },
  hi: { nativeName: 'हिन्दी', flag: 'hi', names: { en:'Hindi', ar:'الهندية', es:'hindi', fr:'hindi', de:'Hindi', zh:'印地语', hi:'हिन्दी' } },
};

const en = {
 home:'Home',practice:'Ranked',simulators:'Simulators',community:'Community',settings:'Settings',profile:'Profile',planUsage:'Plan & Usage',profileMenu:'Profile menu',closeMenu:'Close profile menu',createPost:'Create post',back:'Back',close:'Close',
 welcomeBack:'Welcome back',welcomeBody:'Pick up where you left off, or jump into a new topic.',continueStudying:'Continue studying',continueBody:'Your last session will show up here.',todayGoal:"Today's goal",goalBody:'Set a daily practice goal to build a streak.',practiceSets:'Practice sets',practiceBody:'Course-aligned question sets will be listed here.',flashcards:'Flashcards',flashcardsBody:'Spaced-repetition review decks.',availableSimulators:'Available simulators',simulatorsBody:'Interactive labs and tools for your courses will appear here.',studyGroups:'Study groups',groupsBody:'Find or start a group for your course.',discussionFeed:'Discussion feed',discussionBody:'Posts from your classmates will show up here. Tap the Post button in the tab bar to start one.',
 appearance:'Appearance',theme:'Theme',themeDesc:'Choose how MoeAI looks on this device.',light:'Light',dark:'Dark',system:'System',accentColor:'Accent Color',accentDesc:'Personalize highlights and selected controls.',colorWheel:'Color wheel',presets:'Presets',orange:'Orange',green:'Green',blue:'Blue',red:'Red',purple:'Purple',appLanguage:'App Language',languageDesc:'Choose the language used throughout the app.',chooseLanguage:'Choose language',
 accessibility:'Accessibility',fontSize:'Font Size',fontSizeDesc:'Adjust text throughout the app.',small:'Small',default:'Default',large:'Large',extraLarge:'Extra Large',sampleText:'Lorem Ipsum',chooseFontSize:'Choose font size',textWeight:'Text Weight',textWeightDesc:'Make app text regular or bold.',regular:'Regular',bold:'Bold',motion:'Motion',motionDesc:'Enable interface animations and elastic feedback.',on:'On',off:'Off',selected:'Selected',
 notifications:'Notifications',studyReminders:'Study Reminders',studyRemindersDesc:"Receive reminders when you haven't studied for a while.",quizReminders:'Quiz Reminders',quizRemindersDesc:'Receive reminders when you have upcoming quizzes.',sessionReminders:'Session Reminders',sessionRemindersDesc:'Receive reminders before your scheduled sessions.',
privacyData:'Privacy & Data',dataAiUsage:'Data & AI Usage',dataAiUsageDesc:'Review how your data supports AI features.',downloadData:'Download My Data',downloadDataDesc:'Request a copy of your account data.',deleteData:'Delete Account & Data',deleteDataDesc:'Permanently remove your account and stored data.',information:'Information',whatsNew:"What's New",whatsNewDesc:'See recent features and improvements.',terms:'Terms of Service',termsDesc:'Read the terms that govern use of MoeAI.',privacyPolicy:'Privacy Policy',privacyPolicyDesc:'Learn how your personal information is handled.',licenses:'Licenses',licensesDesc:'View open-source software acknowledgements.',version:'Version',currentVersion:'0.2.3'
};

const ar = { ...en,
 home:'الرئيسية',practice:'التصنيف',simulators:'المحاكاة',community:'المجتمع',settings:'الإعدادات',profile:'الملف الشخصي',planUsage:'الخطة والاستخدام',profileMenu:'قائمة الملف',closeMenu:'إغلاق قائمة الملف',createPost:'إنشاء منشور',back:'رجوع',close:'إغلاق',
 welcomeBack:'مرحبًا بعودتك',welcomeBody:'تابع من حيث توقفت أو ابدأ موضوعًا جديدًا.',continueStudying:'متابعة الدراسة',continueBody:'ستظهر جلستك الأخيرة هنا.',todayGoal:'هدف اليوم',goalBody:'حدد هدفًا يوميًا للمواظبة.',practiceSets:'مجموعات التمارين',practiceBody:'ستظهر هنا تمارين مناسبة لمقرراتك.',flashcards:'البطاقات التعليمية',flashcardsBody:'مراجعة بالتكرار المتباعد.',availableSimulators:'المحاكيات المتاحة',simulatorsBody:'ستظهر هنا المختبرات والأدوات التفاعلية.',studyGroups:'مجموعات الدراسة',groupsBody:'ابحث عن مجموعة لمقررك أو أنشئها.',discussionFeed:'مناقشات المجتمع',discussionBody:'ستظهر منشورات زملائك هنا.',
 appearance:'المظهر',theme:'النسق',themeDesc:'اختر مظهر MoeAI على هذا الجهاز.',light:'فاتح',dark:'داكن',system:'النظام',accentColor:'لون التمييز',accentDesc:'خصص العناصر المميزة.',colorWheel:'عجلة الألوان',presets:'ألوان جاهزة',orange:'برتقالي',green:'أخضر',blue:'أزرق',red:'أحمر',purple:'بنفسجي',appLanguage:'لغة التطبيق',languageDesc:'اختر لغة التطبيق.',chooseLanguage:'اختر اللغة',accessibility:'إمكانية الوصول',fontSize:'حجم الخط',fontSizeDesc:'عدّل حجم النص في التطبيق.',small:'صغير',default:'افتراضي',large:'كبير',extraLarge:'كبير جدًا',chooseFontSize:'اختر حجم الخط',textWeight:'سُمك النص',textWeightDesc:'اجعل النص عاديًا أو عريضًا.',regular:'عادي',bold:'عريض',motion:'الحركة',motionDesc:'فعّل الرسوم المتحركة والاستجابة المرنة.',on:'مفعّل',off:'متوقف',selected:'محدد',notifications:'الإشعارات',studyReminders:'تذكيرات الدراسة',studyRemindersDesc:'تلقّ تذكيرًا عند الانقطاع عن الدراسة.',quizReminders:'تذكيرات الاختبارات',quizRemindersDesc:'تلقّ تذكيرًا بالاختبارات القادمة.',sessionReminders:'تذكيرات الجلسات',sessionRemindersDesc:'تلقّ تذكيرًا قبل الجلسات المجدولة.',privacyData:'الخصوصية والبيانات',dataAiUsage:'استخدام البيانات والذكاء الاصطناعي',dataAiUsageDesc:'راجع كيفية دعم بياناتك لميزات الذكاء الاصطناعي.',downloadData:'تنزيل بياناتي',downloadDataDesc:'اطلب نسخة من بيانات حسابك.',deleteData:'حذف الحساب والبيانات',deleteDataDesc:'احذف حسابك وبياناتك نهائيًا.',information:'معلومات',whatsNew:'ما الجديد',whatsNewDesc:'اطلع على أحدث الميزات والتحسينات.',terms:'شروط الخدمة',termsDesc:'اقرأ شروط استخدام MoeAI.',privacyPolicy:'سياسة الخصوصية',privacyPolicyDesc:'تعرف على كيفية التعامل مع معلوماتك.',licenses:'التراخيص',licensesDesc:'اعرض إقرارات البرمجيات مفتوحة المصدر.',version:'الإصدار'
};

// These languages translate every visible control; shared placeholder dashboard copy
// is intentionally concise so large accessibility text still wraps safely.
const es = { ...en, home:'Inicio',practice:'Clasificatoria',simulators:'Simuladores',community:'Comunidad',settings:'Ajustes',profile:'Perfil',planUsage:'Plan y uso',profileMenu:'Menú de perfil',closeMenu:'Cerrar menú',createPost:'Crear publicación',back:'Atrás',close:'Cerrar',appearance:'Apariencia',theme:'Tema',themeDesc:'Elige cómo se ve MoeAI.',light:'Claro',dark:'Oscuro',system:'Sistema',accentColor:'Color de acento',accentDesc:'Personaliza los controles seleccionados.',colorWheel:'Rueda de color',presets:'Preajustes',orange:'Naranja',green:'Verde',blue:'Azul',red:'Rojo',purple:'Morado',appLanguage:'Idioma de la app',languageDesc:'Elige el idioma de la aplicación.',chooseLanguage:'Elegir idioma',accessibility:'Accesibilidad',fontSize:'Tamaño de fuente',fontSizeDesc:'Ajusta el texto de toda la app.',small:'Pequeño',default:'Predeterminado',large:'Grande',extraLarge:'Muy grande',chooseFontSize:'Elegir tamaño',textWeight:'Grosor del texto',textWeightDesc:'Usa texto normal o negrita.',regular:'Normal',bold:'Negrita',motion:'Movimiento',motionDesc:'Activa animaciones y respuesta elástica.',on:'Activado',off:'Desactivado',selected:'Seleccionado',notifications:'Notificaciones',studyReminders:'Recordatorios de estudio',studyRemindersDesc:'Recibe avisos si no has estudiado por un tiempo.',quizReminders:'Recordatorios de cuestionarios',quizRemindersDesc:'Recibe avisos sobre cuestionarios próximos.',sessionReminders:'Recordatorios de sesiones',sessionRemindersDesc:'Recibe avisos antes de tus sesiones.',privacyData:'Privacidad y datos',dataAiUsage:'Uso de datos e IA',dataAiUsageDesc:'Revisa cómo tus datos apoyan las funciones de IA.',downloadData:'Descargar mis datos',downloadDataDesc:'Solicita una copia de tus datos.',deleteData:'Eliminar cuenta y datos',deleteDataDesc:'Elimina tu cuenta y datos permanentemente.',information:'Información',whatsNew:'Novedades',whatsNewDesc:'Consulta funciones y mejoras recientes.',terms:'Términos de servicio',termsDesc:'Lee los términos de uso de MoeAI.',privacyPolicy:'Política de privacidad',privacyPolicyDesc:'Conoce cómo tratamos tu información.',licenses:'Licencias',licensesDesc:'Consulta los reconocimientos de código abierto.',version:'Versión' };
const fr = { ...en, home:'Accueil',practice:'Classé',simulators:'Simulateurs',community:'Communauté',settings:'Paramètres',profile:'Profil',planUsage:'Forfait et usage',profileMenu:'Menu du profil',closeMenu:'Fermer le menu',createPost:'Créer une publication',back:'Retour',close:'Fermer',appearance:'Apparence',theme:'Thème',themeDesc:"Choisissez l'apparence de MoeAI.",light:'Clair',dark:'Sombre',system:'Système',accentColor:"Couleur d'accent",accentDesc:'Personnalisez les contrôles actifs.',colorWheel:'Roue chromatique',presets:'Préréglages',orange:'Orange',green:'Vert',blue:'Bleu',red:'Rouge',purple:'Violet',appLanguage:"Langue de l'app",languageDesc:"Choisissez la langue de l'application.",chooseLanguage:'Choisir la langue',accessibility:'Accessibilité',fontSize:'Taille du texte',fontSizeDesc:"Ajustez le texte dans toute l'app.",small:'Petite',default:'Par défaut',large:'Grande',extraLarge:'Très grande',chooseFontSize:'Choisir la taille',textWeight:'Graisse du texte',textWeightDesc:'Utilisez du texte normal ou gras.',regular:'Normale',bold:'Gras',motion:'Animations',motionDesc:'Activez les animations et retours élastiques.',on:'Activé',off:'Désactivé',selected:'Sélectionné',notifications:'Notifications',studyReminders:"Rappels d'étude",studyRemindersDesc:"Recevez un rappel après une pause d'étude.",quizReminders:'Rappels de quiz',quizRemindersDesc:'Recevez un rappel pour les quiz à venir.',sessionReminders:'Rappels de sessions',sessionRemindersDesc:'Recevez un rappel avant vos sessions.',privacyData:'Confidentialité et données',dataAiUsage:'Utilisation des données et IA',dataAiUsageDesc:"Consultez l'usage des données par l'IA.",downloadData:'Télécharger mes données',downloadDataDesc:'Demandez une copie de vos données.',deleteData:'Supprimer le compte et les données',deleteDataDesc:'Supprimez définitivement compte et données.',information:'Informations',whatsNew:'Nouveautés',whatsNewDesc:'Découvrez les dernières améliorations.',terms:"Conditions d'utilisation",termsDesc:"Lisez les conditions d'utilisation de MoeAI.",privacyPolicy:'Politique de confidentialité',privacyPolicyDesc:'Découvrez comment vos informations sont traitées.',licenses:'Licences',licensesDesc:'Consultez les mentions open source.',version:'Version' };
const de = { ...en, home:'Start',practice:'Rangliste',simulators:'Simulatoren',community:'Community',settings:'Einstellungen',profile:'Profil',planUsage:'Tarif & Nutzung',profileMenu:'Profilmenü',closeMenu:'Menü schließen',createPost:'Beitrag erstellen',back:'Zurück',close:'Schließen',appearance:'Darstellung',theme:'Design',themeDesc:'Wähle das Erscheinungsbild von MoeAI.',light:'Hell',dark:'Dunkel',system:'System',accentColor:'Akzentfarbe',accentDesc:'Passe aktive Steuerelemente an.',colorWheel:'Farbkreis',presets:'Voreinstellungen',orange:'Orange',green:'Grün',blue:'Blau',red:'Rot',purple:'Violett',appLanguage:'App-Sprache',languageDesc:'Wähle die Sprache der App.',chooseLanguage:'Sprache wählen',accessibility:'Barrierefreiheit',fontSize:'Schriftgröße',fontSizeDesc:'Passe Text in der gesamten App an.',small:'Klein',default:'Standard',large:'Groß',extraLarge:'Sehr groß',chooseFontSize:'Schriftgröße wählen',textWeight:'Schriftstärke',textWeightDesc:'Nutze normale oder fette Schrift.',regular:'Normal',bold:'Fett',motion:'Bewegung',motionDesc:'Aktiviere Animationen und elastisches Feedback.',on:'An',off:'Aus',selected:'Ausgewählt',notifications:'Benachrichtigungen',studyReminders:'Lernerinnerungen',studyRemindersDesc:'Erhalte Erinnerungen nach einer Lernpause.',quizReminders:'Quiz-Erinnerungen',quizRemindersDesc:'Erhalte Erinnerungen an kommende Quizze.',sessionReminders:'Sitzungserinnerungen',sessionRemindersDesc:'Erhalte Erinnerungen vor Sitzungen.',privacyData:'Datenschutz & Daten',dataAiUsage:'Daten- & KI-Nutzung',dataAiUsageDesc:'Prüfe die Datennutzung für KI-Funktionen.',downloadData:'Meine Daten herunterladen',downloadDataDesc:'Fordere eine Kopie deiner Daten an.',deleteData:'Konto & Daten löschen',deleteDataDesc:'Lösche Konto und Daten dauerhaft.',information:'Informationen',whatsNew:'Neuigkeiten',whatsNewDesc:'Sieh neue Funktionen und Verbesserungen.',terms:'Nutzungsbedingungen',termsDesc:'Lies die Bedingungen für MoeAI.',privacyPolicy:'Datenschutzerklärung',privacyPolicyDesc:'Erfahre, wie Informationen verarbeitet werden.',licenses:'Lizenzen',licensesDesc:'Sieh Open-Source-Hinweise.',version:'Version' };
const zh = { ...en, home:'主页',practice:'排位',simulators:'模拟器',community:'社区',settings:'设置',profile:'个人资料',planUsage:'计划与用量',profileMenu:'个人资料菜单',closeMenu:'关闭菜单',createPost:'创建帖子',back:'返回',close:'关闭',appearance:'外观',theme:'主题',themeDesc:'选择 MoeAI 的外观。',light:'浅色',dark:'深色',system:'跟随系统',accentColor:'强调色',accentDesc:'自定义高亮控件。',colorWheel:'色轮',presets:'预设',orange:'橙色',green:'绿色',blue:'蓝色',red:'红色',purple:'紫色',appLanguage:'应用语言',languageDesc:'选择应用中使用的语言。',chooseLanguage:'选择语言',accessibility:'辅助功能',fontSize:'字体大小',fontSizeDesc:'调整整个应用的文字。',small:'小',default:'默认',large:'大',extraLarge:'特大',chooseFontSize:'选择字号',textWeight:'字重',textWeightDesc:'使用常规或粗体。',regular:'常规',bold:'粗体',motion:'动效',motionDesc:'启用动画和弹性反馈。',on:'开',off:'关',selected:'已选',notifications:'通知',studyReminders:'学习提醒',studyRemindersDesc:'长时间未学习时提醒。',quizReminders:'测验提醒',quizRemindersDesc:'提醒即将到来的测验。',sessionReminders:'课程提醒',sessionRemindersDesc:'在预定课程前提醒。',privacyData:'隐私与数据',dataAiUsage:'数据与 AI 使用',dataAiUsageDesc:'查看数据如何支持 AI 功能。',downloadData:'下载我的数据',downloadDataDesc:'申请一份账户数据副本。',deleteData:'删除账户和数据',deleteDataDesc:'永久删除账户和数据。',information:'信息',whatsNew:'新功能',whatsNewDesc:'查看最新功能和改进。',terms:'服务条款',termsDesc:'阅读 MoeAI 使用条款。',privacyPolicy:'隐私政策',privacyPolicyDesc:'了解个人信息的处理方式。',licenses:'开源许可',licensesDesc:'查看开源软件声明。',version:'版本' };
const hi = { ...en, home:'होम',practice:'रैंक्ड',simulators:'सिम्युलेटर',community:'समुदाय',settings:'सेटिंग्स',profile:'प्रोफ़ाइल',planUsage:'प्लान और उपयोग',profileMenu:'प्रोफ़ाइल मेनू',closeMenu:'मेनू बंद करें',createPost:'पोस्ट बनाएँ',back:'वापस',close:'बंद करें',appearance:'दिखावट',theme:'थीम',themeDesc:'MoeAI का रूप चुनें।',light:'लाइट',dark:'डार्क',system:'सिस्टम',accentColor:'एक्सेंट रंग',accentDesc:'हाइलाइट और चयनित कंट्रोल बदलें।',colorWheel:'रंग चक्र',presets:'प्रीसेट',orange:'नारंगी',green:'हरा',blue:'नीला',red:'लाल',purple:'बैंगनी',appLanguage:'ऐप की भाषा',languageDesc:'ऐप में प्रयोग होने वाली भाषा चुनें।',chooseLanguage:'भाषा चुनें',accessibility:'एक्सेसिबिलिटी',fontSize:'फ़ॉन्ट आकार',fontSizeDesc:'पूरे ऐप का टेक्स्ट बदलें।',small:'छोटा',default:'डिफ़ॉल्ट',large:'बड़ा',extraLarge:'बहुत बड़ा',chooseFontSize:'फ़ॉन्ट आकार चुनें',textWeight:'टेक्स्ट का वज़न',textWeightDesc:'सामान्य या बोल्ड टेक्स्ट चुनें।',regular:'सामान्य',bold:'बोल्ड',motion:'मोशन',motionDesc:'एनिमेशन और लचीला फीडबैक चालू करें।',on:'चालू',off:'बंद',selected:'चयनित',notifications:'सूचनाएँ',studyReminders:'अध्ययन रिमाइंडर',studyRemindersDesc:'कुछ समय न पढ़ने पर रिमाइंडर पाएँ।',quizReminders:'क्विज़ रिमाइंडर',quizRemindersDesc:'आने वाली क्विज़ के रिमाइंडर पाएँ।',sessionReminders:'सत्र रिमाइंडर',sessionRemindersDesc:'तय सत्र से पहले रिमाइंडर पाएँ।',privacyData:'गोपनीयता और डेटा',dataAiUsage:'डेटा और AI उपयोग',dataAiUsageDesc:'AI सुविधाओं में डेटा उपयोग देखें।',downloadData:'मेरा डेटा डाउनलोड करें',downloadDataDesc:'अपने डेटा की प्रति माँगें।',deleteData:'खाता और डेटा हटाएँ',deleteDataDesc:'खाता और डेटा स्थायी रूप से हटाएँ।',information:'जानकारी',whatsNew:'नया क्या है',whatsNewDesc:'नई सुविधाएँ और सुधार देखें।',terms:'सेवा की शर्तें',termsDesc:'MoeAI के उपयोग की शर्तें पढ़ें।',privacyPolicy:'गोपनीयता नीति',privacyPolicyDesc:'अपनी जानकारी के उपयोग को समझें।',licenses:'लाइसेंस',licensesDesc:'ओपन-सोर्स आभार देखें।',version:'संस्करण' };

Object.assign(es,{welcomeBack:'Bienvenido de nuevo',welcomeBody:'Continúa donde lo dejaste o explora un tema nuevo.',continueStudying:'Seguir estudiando',continueBody:'Tu última sesión aparecerá aquí.',todayGoal:'Objetivo de hoy',goalBody:'Define una meta diaria para mantener tu racha.',practiceSets:'Series de práctica',practiceBody:'Aquí aparecerán ejercicios para tus cursos.',flashcards:'Tarjetas',flashcardsBody:'Mazos de repaso con repetición espaciada.',availableSimulators:'Simuladores disponibles',simulatorsBody:'Aquí aparecerán laboratorios y herramientas interactivas.',studyGroups:'Grupos de estudio',groupsBody:'Busca o crea un grupo para tu curso.',discussionFeed:'Debates',discussionBody:'Aquí aparecerán las publicaciones de tus compañeros.'});
Object.assign(fr,{welcomeBack:'Bon retour',welcomeBody:'Reprenez où vous en étiez ou explorez un nouveau sujet.',continueStudying:'Continuer à étudier',continueBody:'Votre dernière session apparaîtra ici.',todayGoal:"Objectif du jour",goalBody:'Fixez un objectif quotidien pour garder votre série.',practiceSets:"Séries d'exercices",practiceBody:'Les exercices de vos cours apparaîtront ici.',flashcards:'Cartes mémoire',flashcardsBody:'Révision par répétition espacée.',availableSimulators:'Simulateurs disponibles',simulatorsBody:'Les laboratoires et outils interactifs apparaîtront ici.',studyGroups:"Groupes d'étude",groupsBody:'Trouvez ou créez un groupe pour votre cours.',discussionFeed:'Discussions',discussionBody:'Les publications de vos camarades apparaîtront ici.'});
Object.assign(de,{welcomeBack:'Willkommen zurück',welcomeBody:'Mach dort weiter oder starte ein neues Thema.',continueStudying:'Weiterlernen',continueBody:'Deine letzte Sitzung erscheint hier.',todayGoal:'Heutiges Ziel',goalBody:'Lege ein Tagesziel für deine Serie fest.',practiceSets:'Übungsreihen',practiceBody:'Kursbezogene Aufgaben erscheinen hier.',flashcards:'Karteikarten',flashcardsBody:'Lernkarten mit verteilten Wiederholungen.',availableSimulators:'Verfügbare Simulatoren',simulatorsBody:'Interaktive Labore und Werkzeuge erscheinen hier.',studyGroups:'Lerngruppen',groupsBody:'Finde oder gründe eine Gruppe für deinen Kurs.',discussionFeed:'Diskussionen',discussionBody:'Beiträge deiner Mitschüler erscheinen hier.'});
Object.assign(zh,{welcomeBack:'欢迎回来',welcomeBody:'从上次停止处继续，或开始新主题。',continueStudying:'继续学习',continueBody:'你最近的学习会话将显示在这里。',todayGoal:'今日目标',goalBody:'设置每日练习目标并保持连续学习。',practiceSets:'练习集',practiceBody:'与课程匹配的练习将在这里显示。',flashcards:'闪卡',flashcardsBody:'使用间隔重复复习卡组。',availableSimulators:'可用模拟器',simulatorsBody:'互动实验室和课程工具将在这里显示。',studyGroups:'学习小组',groupsBody:'为你的课程查找或创建小组。',discussionFeed:'讨论',discussionBody:'同学的帖子将在这里显示。'});
Object.assign(hi,{welcomeBack:'फिर से स्वागत है',welcomeBody:'जहाँ छोड़ा था वहीं से जारी रखें या नया विषय चुनें।',continueStudying:'पढ़ाई जारी रखें',continueBody:'आपका पिछला सत्र यहाँ दिखाई देगा।',todayGoal:'आज का लक्ष्य',goalBody:'नियमितता के लिए रोज़ का लक्ष्य तय करें।',practiceSets:'अभ्यास सेट',practiceBody:'आपके पाठ्यक्रम के प्रश्न यहाँ दिखेंगे।',flashcards:'फ़्लैशकार्ड',flashcardsBody:'अंतराल पुनरावृत्ति वाले कार्ड।',availableSimulators:'उपलब्ध सिम्युलेटर',simulatorsBody:'इंटरैक्टिव लैब और उपकरण यहाँ दिखेंगे।',studyGroups:'अध्ययन समूह',groupsBody:'अपने पाठ्यक्रम के लिए समूह खोजें या बनाएँ।',discussionFeed:'चर्चा',discussionBody:'सहपाठियों की पोस्ट यहाँ दिखेंगी।'});
Object.assign(en,{openFullCalendar:'Open full calendar',previousWeek:'Previous week',nextWeek:'Next week',week:'Week',previousMonth:'Previous month',nextMonth:'Next month',closeCalendar:'Close calendar',allDay:'All day',noAllDayEvents:'No all-day events',expandDescription:'Show description',collapseDescription:'Hide description',demoResearchBrief:'Research brief uploaded',demoResearchBriefDesc:'Lorem Ipsum',demoPhysicsLecture:'Physics lecture',demoPhysicsLectureDesc:'Lorem Ipsum',demoLabSubmitted:'Lab report submitted',demoLabSubmittedDesc:'Lorem Ipsum',demoCalculusQuiz:'Calculus quiz',demoCalculusQuizDesc:'Lorem Ipsum',demoStudyGroup:'Study group',demoStudyGroupDesc:'Lorem Ipsum',demoEssayDue:'Essay due',demoEssayDueDesc:'Lorem Ipsum',demoBirthday:'Your birthday',demoBirthdayDesc:'Lorem Ipsum',demoScienceFair:'Science fair',demoScienceFairDesc:'Lorem Ipsum',demoPortfolio:'Design portfolio',demoPortfolioDesc:'Lorem Ipsum',demoBreak:'Mid-term break',demoBreakDesc:'Lorem Ipsum'});
Object.assign(ar,{openFullCalendar:'فتح التقويم الكامل',previousWeek:'الأسبوع السابق',nextWeek:'الأسبوع التالي',week:'الأسبوع',previousMonth:'الشهر السابق',nextMonth:'الشهر التالي',closeCalendar:'إغلاق التقويم',allDay:'طوال اليوم',noAllDayEvents:'لا توجد أحداث طوال اليوم',expandDescription:'إظهار الوصف',collapseDescription:'إخفاء الوصف',demoResearchBrief:'تم رفع موجز البحث',demoResearchBriefDesc:'راجع حزمة المصادر قبل بدء الواجب.',demoPhysicsLecture:'محاضرة الفيزياء',demoPhysicsLectureDesc:'تداخل الموجات وأمثلة الموجات الواقفة.',demoLabSubmitted:'تم تسليم تقرير المختبر',demoLabSubmittedDesc:'تم حفظ إيصال التسليم في مساحة المقرر.',demoCalculusQuiz:'اختبار التفاضل',demoCalculusQuizDesc:'يشمل المشتقات وقاعدة السلسلة والمعدلات المرتبطة.',demoStudyGroup:'مجموعة الدراسة',demoStudyGroupDesc:'مراجعة نهائية مع مجموعة دراسة التفاضل.',demoEssayDue:'موعد تسليم المقال',demoEssayDueDesc:'سلّم المقال النهائي قبل الموعد.',demoBirthday:'عيد ميلادك',demoBirthdayDesc:'تذكير بعيد الميلاد.',demoScienceFair:'معرض العلوم',demoScienceFairDesc:'مشروعات وعروض الطلاب في القاعة الرئيسية.',demoPortfolio:'ملف التصميم',demoPortfolioDesc:'فترة إتاحة الواجب.',demoBreak:'عطلة منتصف الفصل',demoBreakDesc:'لا توجد حصص مجدولة.'});
Object.assign(es,{openFullCalendar:'Abrir calendario completo',previousWeek:'Semana anterior',nextWeek:'Semana siguiente',week:'Semana',previousMonth:'Mes anterior',nextMonth:'Mes siguiente',closeCalendar:'Cerrar calendario',allDay:'Todo el día',noAllDayEvents:'No hay eventos de todo el día',expandDescription:'Mostrar descripción',collapseDescription:'Ocultar descripción',demoResearchBrief:'Informe de investigación publicado',demoResearchBriefDesc:'Revisa las fuentes antes de comenzar la tarea.',demoPhysicsLecture:'Clase de física',demoPhysicsLectureDesc:'Interferencia y ondas estacionarias.',demoLabSubmitted:'Informe de laboratorio entregado',demoLabSubmittedDesc:'El recibo se guardó en el espacio del curso.',demoCalculusQuiz:'Prueba de cálculo',demoCalculusQuizDesc:'Derivadas, regla de la cadena y razones relacionadas.',demoStudyGroup:'Grupo de estudio',demoStudyGroupDesc:'Repaso final con el grupo de cálculo.',demoEssayDue:'Entrega del ensayo',demoEssayDueDesc:'Entrega el ensayo final antes del plazo.',demoBirthday:'Tu cumpleaños',demoBirthdayDesc:'Recordatorio de cumpleaños.',demoScienceFair:'Feria de ciencias',demoScienceFairDesc:'Proyectos y demostraciones en el salón principal.',demoPortfolio:'Portafolio de diseño',demoPortfolioDesc:'Periodo de disponibilidad de la tarea.',demoBreak:'Vacaciones de mitad de curso',demoBreakDesc:'No hay clases programadas.'});
Object.assign(fr,{openFullCalendar:'Ouvrir le calendrier complet',previousWeek:'Semaine précédente',nextWeek:'Semaine suivante',week:'Semaine',previousMonth:'Mois précédent',nextMonth:'Mois suivant',closeCalendar:'Fermer le calendrier',allDay:'Toute la journée',noAllDayEvents:'Aucun événement sur la journée',expandDescription:'Afficher la description',collapseDescription:'Masquer la description',demoResearchBrief:'Sujet de recherche publié',demoResearchBriefDesc:'Consultez les sources avant de commencer le devoir.',demoPhysicsLecture:'Cours de physique',demoPhysicsLectureDesc:'Interférences et ondes stationnaires.',demoLabSubmitted:'Rapport de laboratoire remis',demoLabSubmittedDesc:'Le reçu est enregistré dans l’espace du cours.',demoCalculusQuiz:'Quiz de calcul',demoCalculusQuizDesc:'Dérivées, règle de chaîne et taux liés.',demoStudyGroup:'Groupe d’étude',demoStudyGroupDesc:'Révision finale avec le groupe de calcul.',demoEssayDue:'Dissertation à rendre',demoEssayDueDesc:'Remettez la version finale avant l’échéance.',demoBirthday:'Votre anniversaire',demoBirthdayDesc:'Rappel d’anniversaire.',demoScienceFair:'Salon des sciences',demoScienceFairDesc:'Projets et démonstrations dans le hall principal.',demoPortfolio:'Portfolio de design',demoPortfolioDesc:'Période de disponibilité du devoir.',demoBreak:'Vacances de mi-semestre',demoBreakDesc:'Aucun cours prévu.'});
Object.assign(de,{openFullCalendar:'Vollständigen Kalender öffnen',previousWeek:'Vorherige Woche',nextWeek:'Nächste Woche',week:'Woche',previousMonth:'Vorheriger Monat',nextMonth:'Nächster Monat',closeCalendar:'Kalender schließen',allDay:'Ganztägig',noAllDayEvents:'Keine ganztägigen Termine',expandDescription:'Beschreibung anzeigen',collapseDescription:'Beschreibung ausblenden',demoResearchBrief:'Forschungsauftrag hochgeladen',demoResearchBriefDesc:'Sieh die Quellen vor Beginn der Aufgabe durch.',demoPhysicsLecture:'Physikvorlesung',demoPhysicsLectureDesc:'Interferenz und stehende Wellen.',demoLabSubmitted:'Laborbericht eingereicht',demoLabSubmittedDesc:'Der Beleg wurde im Kursbereich gespeichert.',demoCalculusQuiz:'Analysis-Quiz',demoCalculusQuizDesc:'Ableitungen, Kettenregel und verwandte Raten.',demoStudyGroup:'Lerngruppe',demoStudyGroupDesc:'Abschlusswiederholung mit der Analysis-Gruppe.',demoEssayDue:'Aufsatz fällig',demoEssayDueDesc:'Reiche den Aufsatz vor Ablauf der Frist ein.',demoBirthday:'Dein Geburtstag',demoBirthdayDesc:'Geburtstagserinnerung.',demoScienceFair:'Wissenschaftsmesse',demoScienceFairDesc:'Projekte und Vorführungen in der Haupthalle.',demoPortfolio:'Designportfolio',demoPortfolioDesc:'Verfügbarkeitszeitraum der Aufgabe.',demoBreak:'Semesterpause',demoBreakDesc:'Keine geplanten Kurse.'});
Object.assign(zh,{openFullCalendar:'打开完整日历',previousWeek:'上一周',nextWeek:'下一周',week:'周',previousMonth:'上个月',nextMonth:'下个月',closeCalendar:'关闭日历',allDay:'全天',noAllDayEvents:'没有全天事件',expandDescription:'显示说明',collapseDescription:'隐藏说明',demoResearchBrief:'研究任务已上传',demoResearchBriefDesc:'开始作业前请查看资料包。',demoPhysicsLecture:'物理课',demoPhysicsLectureDesc:'波的干涉和驻波示例。',demoLabSubmitted:'实验报告已提交',demoLabSubmittedDesc:'提交收据已保存到课程空间。',demoCalculusQuiz:'微积分测验',demoCalculusQuizDesc:'涵盖导数、链式法则和相关变化率。',demoStudyGroup:'学习小组',demoStudyGroupDesc:'与微积分学习小组进行最终复习。',demoEssayDue:'论文截止',demoEssayDueDesc:'请在截止时间前提交最终论文。',demoBirthday:'你的生日',demoBirthdayDesc:'生日提醒。',demoScienceFair:'科学展',demoScienceFairDesc:'主大厅内的学生项目和演示。',demoPortfolio:'设计作品集',demoPortfolioDesc:'作业开放时间。',demoBreak:'期中假期',demoBreakDesc:'没有安排课程。'});
Object.assign(hi,{openFullCalendar:'पूरा कैलेंडर खोलें',previousWeek:'पिछला सप्ताह',nextWeek:'अगला सप्ताह',week:'सप्ताह',previousMonth:'पिछला महीना',nextMonth:'अगला महीना',closeCalendar:'कैलेंडर बंद करें',allDay:'पूरा दिन',noAllDayEvents:'पूरे दिन का कोई कार्यक्रम नहीं',expandDescription:'विवरण दिखाएँ',collapseDescription:'विवरण छिपाएँ',demoResearchBrief:'शोध विवरण अपलोड हुआ',demoResearchBriefDesc:'असाइनमेंट शुरू करने से पहले स्रोत देखें।',demoPhysicsLecture:'भौतिकी व्याख्यान',demoPhysicsLectureDesc:'तरंग व्यतिकरण और स्थायी तरंगें।',demoLabSubmitted:'लैब रिपोर्ट जमा हुई',demoLabSubmittedDesc:'जमा रसीद पाठ्यक्रम स्थान में सहेजी गई।',demoCalculusQuiz:'कैलकुलस क्विज़',demoCalculusQuizDesc:'अवकलज, चेन नियम और संबंधित दरें।',demoStudyGroup:'अध्ययन समूह',demoStudyGroupDesc:'कैलकुलस समूह के साथ अंतिम समीक्षा।',demoEssayDue:'निबंध की समय सीमा',demoEssayDueDesc:'समय सीमा से पहले अंतिम निबंध जमा करें।',demoBirthday:'आपका जन्मदिन',demoBirthdayDesc:'जन्मदिन अनुस्मारक।',demoScienceFair:'विज्ञान मेला',demoScienceFairDesc:'मुख्य हॉल में छात्र परियोजनाएँ और प्रदर्शन।',demoPortfolio:'डिज़ाइन पोर्टफोलियो',demoPortfolioDesc:'असाइनमेंट उपलब्धता अवधि।',demoBreak:'मध्यावधि अवकाश',demoBreakDesc:'कोई निर्धारित कक्षा नहीं।'});
Object.assign(en,{download:'Download',downloadAssignment:'Download assignment',noEvents:'No events for this day'});
Object.assign(ar,{download:'تنزيل',downloadAssignment:'تنزيل الواجب',noEvents:'لا توجد أحداث في هذا اليوم'});
Object.assign(es,{download:'Descargar',downloadAssignment:'Descargar tarea',noEvents:'No hay eventos para este día'});
Object.assign(fr,{download:'Télécharger',downloadAssignment:'Télécharger le devoir',noEvents:'Aucun événement ce jour'});
Object.assign(de,{download:'Herunterladen',downloadAssignment:'Aufgabe herunterladen',noEvents:'Keine Termine an diesem Tag'});
Object.assign(zh,{download:'下载',downloadAssignment:'下载作业',noEvents:'当天没有事件'});
Object.assign(hi,{download:'डाउनलोड',downloadAssignment:'असाइनमेंट डाउनलोड करें',noEvents:'इस दिन कोई कार्यक्रम नहीं'});
Object.assign(en,{auto:'Auto'}); Object.assign(ar,{auto:'Auto'}); Object.assign(es,{auto:'Auto'}); Object.assign(fr,{auto:'Auto'}); Object.assign(de,{auto:'Auto'}); Object.assign(zh,{auto:'Auto'}); Object.assign(hi,{auto:'Auto'});
Object.assign(ar,{currentVersion:'0.2.3'}); Object.assign(es,{currentVersion:'0.2.3'}); Object.assign(fr,{currentVersion:'0.2.3'}); Object.assign(de,{currentVersion:'0.2.3'}); Object.assign(zh,{currentVersion:'0.2.3'}); Object.assign(hi,{currentVersion:'0.2.3'});
Object.assign(en,{view:'View',jumpToTime:'Jump To',uploadDate:'Upload date',dueDate:'Due date',submissionDate:'Submission date',eventDate:'Date',fromTo:'Start–end',dateRange:'Date range',notAvailable:'Not available',now:'Now'});
Object.assign(ar,{view:'عرض',jumpToTime:'انتقل إلى',uploadDate:'تاريخ الرفع',dueDate:'تاريخ الاستحقاق',submissionDate:'تاريخ التسليم',eventDate:'التاريخ',fromTo:'البداية–النهاية',dateRange:'نطاق التاريخ',notAvailable:'غير متاح',now:'الآن'});
Object.assign(es,{view:'Ver',jumpToTime:'Saltar a',uploadDate:'Fecha de publicación',dueDate:'Fecha límite',submissionDate:'Fecha de entrega',eventDate:'Fecha',fromTo:'Inicio–fin',dateRange:'Rango de fechas',notAvailable:'No disponible',now:'Ahora'});
Object.assign(fr,{view:'Voir',jumpToTime:'Aller à',uploadDate:'Date de publication',dueDate:"Date d’échéance",submissionDate:'Date de remise',eventDate:'Date',fromTo:'Début–fin',dateRange:'Période',notAvailable:'Indisponible',now:'Maintenant'});
Object.assign(de,{view:'Ansehen',jumpToTime:'Springen zu',uploadDate:'Upload-Datum',dueDate:'Fälligkeitsdatum',submissionDate:'Abgabedatum',eventDate:'Datum',fromTo:'Start–Ende',dateRange:'Datumsbereich',notAvailable:'Nicht verfügbar',now:'Jetzt'});
Object.assign(zh,{view:'查看',jumpToTime:'跳转到',uploadDate:'上传日期',dueDate:'截止日期',submissionDate:'提交日期',eventDate:'日期',fromTo:'开始–结束',dateRange:'日期范围',notAvailable:'不可用',now:'现在'});
Object.assign(hi,{view:'देखें',jumpToTime:'यहाँ जाएँ',uploadDate:'अपलोड तिथि',dueDate:'अंतिम तिथि',submissionDate:'जमा करने की तिथि',eventDate:'तिथि',fromTo:'शुरू–समाप्त',dateRange:'तिथि सीमा',notAvailable:'उपलब्ध नहीं',now:'अभी'});
Object.assign(en,{viewFile:'View file',jumpToTime:'Jump To',dummyDescription:'Lorem Ipsum'});
Object.assign(ar,{viewFile:'عرض الملف',jumpToTime:'انتقل إلى',dummyDescription:'Lorem Ipsum'});
Object.assign(es,{viewFile:'Ver archivo',jumpToTime:'Saltar a',dummyDescription:'Lorem Ipsum'});
Object.assign(fr,{viewFile:'Voir le fichier',jumpToTime:'Aller à',dummyDescription:'Lorem Ipsum'});
Object.assign(de,{viewFile:'Datei ansehen',jumpToTime:'Springen zu',dummyDescription:'Lorem Ipsum'});
Object.assign(zh,{viewFile:'查看文件',jumpToTime:'跳转到',dummyDescription:'Lorem Ipsum'});
Object.assign(hi,{viewFile:'फ़ाइल देखें',jumpToTime:'यहाँ जाएँ',dummyDescription:'Lorem Ipsum'});
Object.assign(en,{date:'Date',time:'Time',hour:'Hour',minute:'Minute',period:'AM or PM',month:'Month',day:'Day',year:'Year',cancel:'Cancel',confirm:'Confirm',done:'Done',delete:'Delete',ok:'OK',start:'Start',end:'End',fromTo:'Start–end',startEnd:'Start–end',newEvent:'New event',title:'Title',eventTitlePlaceholder:'Event title',selectStartingTime:'Select Starting time',selectEndingTime:'Select Ending time',invalidTimeRange:'Invalid time range',endAfterStart:'The ending date and time must be after the starting date and time.',eventTitleRequired:'Title required',eventTitleRequiredDesc:'Enter a title before saving this event.',deleteEvent:'Delete event?',deleteEventConfirm:'This event will be permanently removed from your calendar.',addEvent:'Add event'});
Object.assign(ar,{date:'التاريخ',time:'الوقت',hour:'الساعة',minute:'الدقيقة',period:'صباحًا أو مساءً',month:'الشهر',day:'اليوم',year:'السنة',cancel:'إلغاء',confirm:'تأكيد',done:'تم',delete:'حذف',ok:'حسنًا',start:'البداية',end:'النهاية',fromTo:'البداية–النهاية',startEnd:'البداية–النهاية',newEvent:'حدث جديد',title:'العنوان',eventTitlePlaceholder:'عنوان الحدث',selectStartingTime:'اختر وقت البداية',selectEndingTime:'اختر وقت النهاية',invalidTimeRange:'نطاق زمني غير صالح',endAfterStart:'يجب أن يكون تاريخ ووقت النهاية بعد تاريخ ووقت البداية.',eventTitleRequired:'العنوان مطلوب',eventTitleRequiredDesc:'أدخل عنوانًا قبل حفظ هذا الحدث.',deleteEvent:'حذف الحدث؟',deleteEventConfirm:'سيُحذف هذا الحدث نهائيًا من تقويمك.',addEvent:'إضافة حدث'});
Object.assign(es,{date:'Fecha',time:'Hora',hour:'Hora',minute:'Minuto',period:'a. m. o p. m.',month:'Mes',day:'Día',year:'Año',cancel:'Cancelar',confirm:'Confirmar',done:'Listo',delete:'Eliminar',ok:'Aceptar',start:'Inicio',end:'Fin',startEnd:'Inicio–fin',newEvent:'Nuevo evento',title:'Título',eventTitlePlaceholder:'Título del evento',selectStartingTime:'Seleccionar hora de inicio',selectEndingTime:'Seleccionar hora de fin',invalidTimeRange:'Intervalo no válido',endAfterStart:'La fecha y hora de fin deben ser posteriores al inicio.',eventTitleRequired:'Título obligatorio',eventTitleRequiredDesc:'Escribe un título antes de guardar el evento.',deleteEvent:'¿Eliminar evento?',deleteEventConfirm:'Este evento se eliminará permanentemente del calendario.',addEvent:'Añadir evento'});
Object.assign(fr,{date:'Date',time:'Heure',hour:'Heure',minute:'Minute',period:'AM ou PM',month:'Mois',day:'Jour',year:'Année',cancel:'Annuler',confirm:'Confirmer',done:'Terminé',delete:'Supprimer',ok:'OK',start:'Début',end:'Fin',startEnd:'Début–fin',newEvent:'Nouvel événement',title:'Titre',eventTitlePlaceholder:"Titre de l’événement",selectStartingTime:'Sélectionner l’heure de début',selectEndingTime:'Sélectionner l’heure de fin',invalidTimeRange:'Période non valide',endAfterStart:'La date et l’heure de fin doivent suivre celles du début.',eventTitleRequired:'Titre requis',eventTitleRequiredDesc:'Saisissez un titre avant d’enregistrer cet événement.',deleteEvent:'Supprimer l’événement ?',deleteEventConfirm:'Cet événement sera définitivement supprimé de votre calendrier.',addEvent:'Ajouter un événement'});
Object.assign(de,{date:'Datum',time:'Uhrzeit',hour:'Stunde',minute:'Minute',period:'AM oder PM',month:'Monat',day:'Tag',year:'Jahr',cancel:'Abbrechen',confirm:'Bestätigen',done:'Fertig',delete:'Löschen',ok:'OK',start:'Start',end:'Ende',startEnd:'Start–Ende',newEvent:'Neuer Termin',title:'Titel',eventTitlePlaceholder:'Termintitel',selectStartingTime:'Startzeit auswählen',selectEndingTime:'Endzeit auswählen',invalidTimeRange:'Ungültiger Zeitraum',endAfterStart:'Enddatum und -zeit müssen nach Startdatum und -zeit liegen.',eventTitleRequired:'Titel erforderlich',eventTitleRequiredDesc:'Gib vor dem Speichern einen Titel ein.',deleteEvent:'Termin löschen?',deleteEventConfirm:'Dieser Termin wird dauerhaft aus deinem Kalender gelöscht.',addEvent:'Termin hinzufügen'});
Object.assign(zh,{date:'日期',time:'时间',hour:'小时',minute:'分钟',period:'上午或下午',month:'月份',day:'日',year:'年份',cancel:'取消',confirm:'确认',done:'完成',delete:'删除',ok:'确定',start:'开始',end:'结束',startEnd:'开始–结束',newEvent:'新建事件',title:'标题',eventTitlePlaceholder:'事件标题',selectStartingTime:'选择开始时间',selectEndingTime:'选择结束时间',invalidTimeRange:'时间范围无效',endAfterStart:'结束日期和时间必须晚于开始日期和时间。',eventTitleRequired:'需要标题',eventTitleRequiredDesc:'请先输入标题再保存此事件。',deleteEvent:'删除事件？',deleteEventConfirm:'此事件将从日历中永久删除。',addEvent:'添加事件'});
Object.assign(hi,{date:'तारीख',time:'समय',hour:'घंटा',minute:'मिनट',period:'AM या PM',month:'महीना',day:'दिन',year:'वर्ष',cancel:'रद्द करें',confirm:'पुष्टि करें',done:'पूर्ण',delete:'हटाएँ',ok:'ठीक है',start:'शुरू',end:'समाप्त',startEnd:'शुरू–समाप्त',newEvent:'नया कार्यक्रम',title:'शीर्षक',eventTitlePlaceholder:'कार्यक्रम का शीर्षक',selectStartingTime:'शुरू होने का समय चुनें',selectEndingTime:'समाप्ति समय चुनें',invalidTimeRange:'अमान्य समय सीमा',endAfterStart:'समाप्ति की तारीख और समय शुरुआत के बाद होना चाहिए।',eventTitleRequired:'शीर्षक आवश्यक है',eventTitleRequiredDesc:'कार्यक्रम सहेजने से पहले शीर्षक दर्ज करें।',deleteEvent:'कार्यक्रम हटाएँ?',deleteEventConfirm:'यह कार्यक्रम आपके कैलेंडर से स्थायी रूप से हट जाएगा।',addEvent:'कार्यक्रम जोड़ें'});

Object.assign(en,{totalProgress:'Total progress',lecturesOutOf:'{completed} out of {total} lectures',assignments:'Assignments',quizzes:'Quizzes',createSubject:'Create subject',renameSubject:'Rename subject',subjectName:'Subject name',newLectureChat:'New lecture chat',lectureName:'Lecture or lesson name',startNewChat:'Start a new chat',uploadFiles:'Upload files',lectureCreated:'Created',lectureFiles:'Files',noFiles:'No files attached',deleteSubject:'Delete subject?',deleteSubjectConfirm:'This subject, its lectures, and all chat history will be permanently deleted.',deleteLecture:'Delete lecture?',deleteLectureConfirm:'This lecture and all of its chat history will be permanently deleted.'});
Object.assign(ar,{totalProgress:'التقدم الكلي',lecturesOutOf:'{completed} من أصل {total} محاضرة',assignments:'الواجبات',quizzes:'الاختبارات',createSubject:'إنشاء مادة',renameSubject:'إعادة تسمية المادة',subjectName:'اسم المادة',newLectureChat:'محادثة محاضرة جديدة',lectureName:'اسم المحاضرة أو الدرس',startNewChat:'بدء محادثة جديدة',uploadFiles:'رفع ملفات',lectureCreated:'تاريخ الإنشاء',lectureFiles:'الملفات',noFiles:'لا توجد ملفات مرفقة',deleteSubject:'حذف المادة؟',deleteSubjectConfirm:'سيتم حذف هذه المادة ومحاضراتها وكل سجل المحادثات نهائيًا.',deleteLecture:'حذف المحاضرة؟',deleteLectureConfirm:'سيتم حذف هذه المحاضرة وكل سجل محادثاتها نهائيًا.'});
Object.assign(es,{totalProgress:'Progreso total',lecturesOutOf:'{completed} de {total} clases',assignments:'Tareas',quizzes:'Cuestionarios',createSubject:'Crear asignatura',renameSubject:'Renombrar asignatura',subjectName:'Nombre de la asignatura',newLectureChat:'Nuevo chat de clase',lectureName:'Nombre de la clase o lección',startNewChat:'Iniciar un chat nuevo',uploadFiles:'Subir archivos',lectureCreated:'Creada',lectureFiles:'Archivos',noFiles:'No hay archivos adjuntos',deleteSubject:'¿Eliminar asignatura?',deleteSubjectConfirm:'La asignatura, sus clases y todo el historial se eliminarán permanentemente.',deleteLecture:'¿Eliminar clase?',deleteLectureConfirm:'La clase y todo su historial se eliminarán permanentemente.'});
Object.assign(fr,{totalProgress:'Progression totale',lecturesOutOf:'{completed} cours sur {total}',assignments:'Devoirs',quizzes:'Quiz',createSubject:'Créer une matière',renameSubject:'Renommer la matière',subjectName:'Nom de la matière',newLectureChat:'Nouveau chat de cours',lectureName:'Nom du cours ou de la leçon',startNewChat:'Démarrer un nouveau chat',uploadFiles:'Ajouter des fichiers',lectureCreated:'Créé',lectureFiles:'Fichiers',noFiles:'Aucun fichier joint',deleteSubject:'Supprimer la matière ?',deleteSubjectConfirm:'Cette matière, ses cours et tout l’historique seront définitivement supprimés.',deleteLecture:'Supprimer le cours ?',deleteLectureConfirm:'Ce cours et tout son historique seront définitivement supprimés.'});
Object.assign(de,{totalProgress:'Gesamtfortschritt',lecturesOutOf:'{completed} von {total} Vorlesungen',assignments:'Aufgaben',quizzes:'Quizze',createSubject:'Fach erstellen',renameSubject:'Fach umbenennen',subjectName:'Fachname',newLectureChat:'Neuer Vorlesungschat',lectureName:'Name der Vorlesung oder Lektion',startNewChat:'Neuen Chat starten',uploadFiles:'Dateien hochladen',lectureCreated:'Erstellt',lectureFiles:'Dateien',noFiles:'Keine Dateien angehängt',deleteSubject:'Fach löschen?',deleteSubjectConfirm:'Dieses Fach, seine Vorlesungen und der gesamte Chatverlauf werden dauerhaft gelöscht.',deleteLecture:'Vorlesung löschen?',deleteLectureConfirm:'Diese Vorlesung und ihr gesamter Chatverlauf werden dauerhaft gelöscht.'});
Object.assign(zh,{totalProgress:'总进度',lecturesOutOf:'已完成 {completed} 节，共 {total} 节',assignments:'作业',quizzes:'测验',createSubject:'创建科目',renameSubject:'重命名科目',subjectName:'科目名称',newLectureChat:'新建课程聊天',lectureName:'课程或课时名称',startNewChat:'开始新聊天',uploadFiles:'上传文件',lectureCreated:'创建时间',lectureFiles:'文件',noFiles:'没有附件',deleteSubject:'删除科目？',deleteSubjectConfirm:'此科目、课程和全部聊天记录将被永久删除。',deleteLecture:'删除课程？',deleteLectureConfirm:'此课程及其全部聊天记录将被永久删除。'});
Object.assign(hi,{totalProgress:'कुल प्रगति',lecturesOutOf:'{total} में से {completed} व्याख्यान',assignments:'असाइनमेंट',quizzes:'क्विज़',createSubject:'विषय बनाएँ',renameSubject:'विषय का नाम बदलें',subjectName:'विषय का नाम',newLectureChat:'नई व्याख्यान चैट',lectureName:'व्याख्यान या पाठ का नाम',startNewChat:'नई चैट शुरू करें',uploadFiles:'फ़ाइलें अपलोड करें',lectureCreated:'बनाया गया',lectureFiles:'फ़ाइलें',noFiles:'कोई फ़ाइल संलग्न नहीं',deleteSubject:'विषय हटाएँ?',deleteSubjectConfirm:'यह विषय, इसके व्याख्यान और पूरा चैट इतिहास स्थायी रूप से हट जाएगा।',deleteLecture:'व्याख्यान हटाएँ?',deleteLectureConfirm:'यह व्याख्यान और इसका पूरा चैट इतिहास स्थायी रूप से हट जाएगा।'});

Object.assign(en,{lectureNumber:'Lecture {number}'});
Object.assign(ar,{lectureNumber:'المحاضرة {number}'});
Object.assign(es,{lectureNumber:'Clase {number}'});
Object.assign(fr,{lectureNumber:'Cours {number}'});
Object.assign(de,{lectureNumber:'Vorlesung {number}'});
Object.assign(zh,{lectureNumber:'第 {number} 讲'});
Object.assign(hi,{lectureNumber:'व्याख्यान {number}'});

Object.assign(en,{chatHistory:'Chat history',newChat:'New chat',messagePlaceholder:'Message MoeAI',sendMessage:'Send message',attachFiles:'Attach files',aiUnavailable:"This feature isn't currently available",emptyChat:'Ask MoeAI about this lecture.',closeChat:'Close chat',openChatHistory:'Open chat history'});
Object.assign(ar,{chatHistory:'سجل المحادثات',newChat:'محادثة جديدة',messagePlaceholder:'راسل MoeAI',sendMessage:'إرسال الرسالة',attachFiles:'إرفاق ملفات',aiUnavailable:'هذه الميزة غير متاحة حاليًا',emptyChat:'اسأل MoeAI عن هذه المحاضرة.',closeChat:'إغلاق المحادثة',openChatHistory:'فتح سجل المحادثات'});
Object.assign(es,{chatHistory:'Historial de chats',newChat:'Nuevo chat',messagePlaceholder:'Mensaje para MoeAI',sendMessage:'Enviar mensaje',attachFiles:'Adjuntar archivos',aiUnavailable:'Esta función no está disponible actualmente',emptyChat:'Pregunta a MoeAI sobre esta clase.',closeChat:'Cerrar chat',openChatHistory:'Abrir historial de chats'});
Object.assign(fr,{chatHistory:'Historique des discussions',newChat:'Nouvelle discussion',messagePlaceholder:'Message à MoeAI',sendMessage:'Envoyer le message',attachFiles:'Joindre des fichiers',aiUnavailable:"Cette fonctionnalité n’est pas disponible actuellement",emptyChat:'Interrogez MoeAI sur ce cours.',closeChat:'Fermer la discussion',openChatHistory:'Ouvrir l’historique'});
Object.assign(de,{chatHistory:'Chatverlauf',newChat:'Neuer Chat',messagePlaceholder:'Nachricht an MoeAI',sendMessage:'Nachricht senden',attachFiles:'Dateien anhängen',aiUnavailable:'Diese Funktion ist derzeit nicht verfügbar',emptyChat:'Frage MoeAI zu dieser Vorlesung.',closeChat:'Chat schließen',openChatHistory:'Chatverlauf öffnen'});
Object.assign(zh,{chatHistory:'聊天记录',newChat:'新聊天',messagePlaceholder:'给 MoeAI 发消息',sendMessage:'发送消息',attachFiles:'附加文件',aiUnavailable:'此功能目前不可用',emptyChat:'向 MoeAI 询问本课程。',closeChat:'关闭聊天',openChatHistory:'打开聊天记录'});
Object.assign(hi,{chatHistory:'चैट इतिहास',newChat:'नई चैट',messagePlaceholder:'MoeAI को संदेश भेजें',sendMessage:'संदेश भेजें',attachFiles:'फ़ाइलें जोड़ें',aiUnavailable:'यह सुविधा अभी उपलब्ध नहीं है',emptyChat:'इस व्याख्यान के बारे में MoeAI से पूछें।',closeChat:'चैट बंद करें',openChatHistory:'चैट इतिहास खोलें'});

Object.assign(en,{pinned:'Pinned',recent:'Recent',renameChat:'Rename chat',chatName:'Chat name',pinChat:'Pin chat',unpinChat:'Unpin chat'});
Object.assign(ar,{pinned:'المثبتة',recent:'الأخيرة',renameChat:'إعادة تسمية المحادثة',chatName:'اسم المحادثة',pinChat:'تثبيت المحادثة',unpinChat:'إلغاء تثبيت المحادثة'});
Object.assign(es,{pinned:'Fijados',recent:'Recientes',renameChat:'Renombrar chat',chatName:'Nombre del chat',pinChat:'Fijar chat',unpinChat:'Desfijar chat'});
Object.assign(fr,{pinned:'Épinglés',recent:'Récents',renameChat:'Renommer la discussion',chatName:'Nom de la discussion',pinChat:'Épingler',unpinChat:'Désépingler'});
Object.assign(de,{pinned:'Angepinnt',recent:'Zuletzt',renameChat:'Chat umbenennen',chatName:'Chatname',pinChat:'Chat anpinnen',unpinChat:'Chat lösen'});
Object.assign(zh,{pinned:'已置顶',recent:'最近',renameChat:'重命名聊天',chatName:'聊天名称',pinChat:'置顶聊天',unpinChat:'取消置顶'});
Object.assign(hi,{pinned:'पिन किए गए',recent:'हाल के',renameChat:'चैट का नाम बदलें',chatName:'चैट का नाम',pinChat:'चैट पिन करें',unpinChat:'चैट अनपिन करें'});

Object.assign(en,{deleteChat:'Delete chat?',deleteChatConfirm:'This chat and all of its messages will be permanently deleted.',aiThinking:'MoeAI is thinking',copyMessage:'Copy message',copied:'Copied!'});
Object.assign(ar,{deleteChat:'حذف المحادثة؟',deleteChatConfirm:'سيتم حذف هذه المحادثة وجميع رسائلها نهائيًا.',aiThinking:'MoeAI يفكر',copyMessage:'نسخ الرسالة',copied:'تم النسخ!'});
Object.assign(es,{deleteChat:'¿Eliminar chat?',deleteChatConfirm:'Este chat y todos sus mensajes se eliminarán permanentemente.',aiThinking:'MoeAI está pensando',copyMessage:'Copiar mensaje',copied:'¡Copiado!'});
Object.assign(fr,{deleteChat:'Supprimer la discussion ?',deleteChatConfirm:'Cette discussion et tous ses messages seront définitivement supprimés.',aiThinking:'MoeAI réfléchit',copyMessage:'Copier le message',copied:'Copié !'});
Object.assign(de,{deleteChat:'Chat löschen?',deleteChatConfirm:'Dieser Chat und alle seine Nachrichten werden dauerhaft gelöscht.',aiThinking:'MoeAI denkt nach',copyMessage:'Nachricht kopieren',copied:'Kopiert!'});
Object.assign(zh,{deleteChat:'删除聊天？',deleteChatConfirm:'此聊天及其全部消息将被永久删除。',aiThinking:'MoeAI 正在思考',copyMessage:'复制消息',copied:'已复制！'});
Object.assign(hi,{deleteChat:'चैट हटाएँ?',deleteChatConfirm:'यह चैट और इसके सभी संदेश स्थायी रूप से हटा दिए जाएँगे।',aiThinking:'MoeAI सोच रहा है',copyMessage:'संदेश कॉपी करें',copied:'कॉपी हो गया!'});

const CHAT_LOREM = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nSed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\nUt enim ad minim veniam, quis nostrud exercitation ullamco.\nLaboris nisi ut aliquip ex ea commodo consequat.\nDuis aute irure dolor in reprehenderit in voluptate velit esse.\nCillum dolore eu fugiat nulla pariatur.\nExcepteur sint occaecat cupidatat non proident.';
Object.assign(en,{aiUnavailable:CHAT_LOREM,camera:'Camera',images:'Images',files:'Files',attachment:'Attachment',holdToDictate:'Hold to dictate',voiceUnavailable:'Speech recognition unavailable',voiceUnavailableDesc:'Speech recognition is unavailable or microphone permission was not granted on this device.',cameraPermission:'Camera permission required',cameraPermissionDesc:'Allow camera access to take a photo for this chat.',messageNavigator:'Open sent-message navigator'});
Object.assign(ar,{aiUnavailable:CHAT_LOREM,camera:'الكاميرا',images:'الصور',files:'الملفات',attachment:'مرفق',holdToDictate:'اضغط مطولًا للإملاء',voiceUnavailable:'التعرّف على الكلام غير متاح',voiceUnavailableDesc:'التعرّف على الكلام غير متاح أو لم يُمنح إذن الميكروفون على هذا الجهاز.',cameraPermission:'إذن الكاميرا مطلوب',cameraPermissionDesc:'اسمح بالوصول إلى الكاميرا لالتقاط صورة لهذه المحادثة.',messageNavigator:'فتح متصفح الرسائل المرسلة'});
Object.assign(es,{aiUnavailable:CHAT_LOREM,camera:'Cámara',images:'Imágenes',files:'Archivos',attachment:'Adjunto',holdToDictate:'Mantén pulsado para dictar',voiceUnavailable:'Reconocimiento de voz no disponible',voiceUnavailableDesc:'El reconocimiento de voz no está disponible o no se concedió permiso para usar el micrófono.',cameraPermission:'Se requiere permiso de cámara',cameraPermissionDesc:'Permite el acceso a la cámara para tomar una foto para este chat.',messageNavigator:'Abrir navegador de mensajes enviados'});
Object.assign(fr,{aiUnavailable:CHAT_LOREM,camera:'Appareil photo',images:'Images',files:'Fichiers',attachment:'Pièce jointe',holdToDictate:'Maintenir pour dicter',voiceUnavailable:'Reconnaissance vocale indisponible',voiceUnavailableDesc:'La reconnaissance vocale est indisponible ou l’autorisation du microphone n’a pas été accordée.',cameraPermission:'Autorisation de la caméra requise',cameraPermissionDesc:'Autorisez la caméra pour prendre une photo pour cette discussion.',messageNavigator:'Ouvrir le navigateur des messages envoyés'});
Object.assign(de,{aiUnavailable:CHAT_LOREM,camera:'Kamera',images:'Bilder',files:'Dateien',attachment:'Anhang',holdToDictate:'Zum Diktieren gedrückt halten',voiceUnavailable:'Spracherkennung nicht verfügbar',voiceUnavailableDesc:'Die Spracherkennung ist nicht verfügbar oder die Mikrofonberechtigung wurde nicht erteilt.',cameraPermission:'Kameraberechtigung erforderlich',cameraPermissionDesc:'Erlaube den Kamerazugriff, um ein Foto für diesen Chat aufzunehmen.',messageNavigator:'Navigator für gesendete Nachrichten öffnen'});
Object.assign(zh,{aiUnavailable:CHAT_LOREM,camera:'相机',images:'图片',files:'文件',attachment:'附件',holdToDictate:'按住以听写',voiceUnavailable:'语音识别不可用',voiceUnavailableDesc:'此设备不支持语音识别，或尚未授予麦克风权限。',cameraPermission:'需要相机权限',cameraPermissionDesc:'允许访问相机以为此聊天拍摄照片。',messageNavigator:'打开已发送消息导航'});
Object.assign(hi,{aiUnavailable:CHAT_LOREM,camera:'कैमरा',images:'चित्र',files:'फ़ाइलें',attachment:'अटैचमेंट',holdToDictate:'बोलकर लिखने के लिए दबाए रखें',voiceUnavailable:'वाक् पहचान उपलब्ध नहीं है',voiceUnavailableDesc:'इस डिवाइस पर वाक् पहचान उपलब्ध नहीं है या माइक्रोफ़ोन की अनुमति नहीं दी गई है।',cameraPermission:'कैमरा अनुमति आवश्यक है',cameraPermissionDesc:'इस चैट के लिए फ़ोटो लेने हेतु कैमरा एक्सेस की अनुमति दें।',messageNavigator:'भेजे गए संदेशों का नेविगेटर खोलें'});

export const translations = { en, ar, es, fr, de, zh, hi };
export const SUPPORTED_LANGUAGES = Object.keys(LANGUAGE_META);

// Interactive replies: cards, streaming controls and follow-ups. Other locales
// fall back to English through t() until they are translated.
Object.assign(en, {
  blockVisualizer: 'Visualizer', blockPhet: 'Simulation', phetUnknown: 'This simulation could not be found.', phetOpen: 'Open on PhET', phetTell: 'Tell MoeAI what I saw', phetExplored: 'I explored it', phetAsk: 'I tried the {title} simulation ({done}). What should I have noticed, and what does it show about the concept?', blockChart: 'Chart', blockDiagram: 'Diagram', blockSteps: 'Steps', blockQuiz: 'Quick check',
  block3d: '3D scene', blockAnimation: 'Animation', blockCode: 'Code', blockRun: 'Run', blockStop: 'Stop', blockExpand: 'Full screen',
  blockDownload: 'Download', blockCopy: 'Copy', blockFix: 'Fix it', blockBuilding: 'Building the {what}…',
  blockFixPrompt: 'The {what} you made shows an error: "{error}". Please fix it and send the whole {what} again.',
  regenerate: 'Regenerate', tryAgain: 'Try again', replyStopped: 'Stopped · regenerate', stopReply: 'Stop replying',
  blockOffline: "This card's tools could not be downloaded. Check your connection.",
  followExplain: 'Explain it differently', followExample: 'Give me an example', followVisual: 'Show me visually', followQuiz: 'Quiz me on this',
});
Object.assign(ar, {
  blockVisualizer: 'محاكاة تفاعلية', blockPhet: 'محاكاة', phetUnknown: 'مش لاقي المحاكاة دي.', phetOpen: 'افتح على PhET', phetTell: 'قول لـ MoeAI شفت إيه', phetExplored: 'جربتها', phetAsk: 'جربت محاكاة {title} ({done}). المفروض ألاحظ إيه، وده بيوضح إيه في الفكرة؟', blockChart: 'رسم بياني', blockDiagram: 'مخطط', blockSteps: 'خطوات', blockQuiz: 'سؤال سريع',
  block3d: 'مشهد ثلاثي الأبعاد', blockAnimation: 'شرح متحرك', blockCode: 'كود', blockRun: 'تشغيل', blockStop: 'إيقاف', blockExpand: 'ملء الشاشة',
  blockDownload: 'تحميل', blockCopy: 'نسخ', blockFix: 'صلّحها', blockBuilding: 'بيتعمل الـ{what}…',
  blockFixPrompt: 'الـ{what} اللي عملته فيه error: "{error}". صلّحه وابعته كامل تاني.',
  regenerate: 'إعادة الإجابة', tryAgain: 'جرّب تاني', replyStopped: 'اتوقف · أعد الإجابة', stopReply: 'وقف الرد',
  blockOffline: 'مقدرناش نحمّل أدوات الكارت ده. اتأكد من النت.',
  followExplain: 'اشرحها بطريقة تانية', followExample: 'اديني مثال', followVisual: 'وريهالي بصريًا', followQuiz: 'اختبرني فيها',
});

// Account and sync.
Object.assign(en, {
  guest: 'Guest', signInShort: 'Tap to sign in', student: 'Student', signIn: 'Sign in', createAccount: 'Create account', yourAccount: 'Your account',
  accountPitch: 'Sign in to keep your courses, progress, chats and calendar on every device, and so MoeAI remembers how you learn.',
  yourName: 'Your name', email: 'Email', password: 'Password', continueGoogle: 'Continue with Google', signInUniversity: 'Sign in with your university', nudgeGo: "Let's go", nudgeLater: 'Later', nudgeResume: "You're {percent}% through {lecture} in {subject}. Want a 5-minute recap so you can finish it today?", nudgeResumePrompt: 'Give me a 5-minute recap of {lecture} ({subject}) so I can finish it, then one question to check I understood.', fromYourCourse: 'FROM YOUR COURSE MATERIAL', orPersonal: 'or use a personal account', universityLinked: 'Your courses and lectures come from your faculty.',
  noAccountYet: 'New here? Create an account', haveAccount: 'Already have an account? Sign in', signOut: 'Sign out',
  accountError: 'Something went wrong. Try again.', syncSaved: 'Saved to your account', syncSaving: 'Saving…',
  syncOffline: 'Offline, your changes will save when you are back online',
  syncExplain: 'Courses, lecture progress, chats, calendar events and settings sync to your account. This device keeps its own copy too.',
});
Object.assign(ar, {
  guest: 'زائر', signInShort: 'اضغط لتسجيل الدخول', student: 'طالب', signIn: 'تسجيل الدخول', createAccount: 'إنشاء حساب', yourAccount: 'حسابك',
  accountPitch: 'سجّل دخولك عشان موادك وتقدمك ومحادثاتك وتقويمك يبقوا معاك على أي جهاز، وعشان MoeAI يفتكر إزاي بتذاكر.',
  yourName: 'اسمك', email: 'الإيميل', password: 'كلمة السر', continueGoogle: 'كمّل بجوجل', signInUniversity: 'سجّل دخول بحساب جامعتك', nudgeGo: 'يلا بينا', nudgeLater: 'بعدين', nudgeResume: 'خلصت {percent}% من {lecture} في {subject}. تحب ملخص في ٥ دقايق عشان تخلصها النهارده؟', nudgeResumePrompt: 'اديني ملخص في ٥ دقايق لـ {lecture} ({subject}) عشان أخلصها، وبعدين سؤال واحد تتأكد إني فهمت.', fromYourCourse: 'من مادة الكورس بتاعك', orPersonal: 'أو استخدم حساب شخصي', universityLinked: 'موادك ومحاضراتك جاية من كليتك.',
  noAccountYet: 'جديد هنا؟ اعمل حساب', haveAccount: 'عندك حساب؟ سجّل دخول', signOut: 'تسجيل الخروج',
  accountError: 'حصلت مشكلة، جرّب تاني.', syncSaved: 'متسجّل في حسابك', syncSaving: 'بيتحفظ…',
  syncOffline: 'مفيش نت، التغييرات هتتحفظ أول ما النت يرجع',
  syncExplain: 'المواد وتقدم المحاضرات والمحادثات والتقويم والإعدادات بتتحفظ في حسابك، والجهاز ده كمان محتفظ بنسخة.',
});

// Account: full onboarding lives on the site; the sheet links into it.
Object.assign(en, {
  continueApple: 'Continue with Apple', finishSetup: 'Finish setting up your account', accountSettings: 'Account settings',
  createAccountFull: 'Create an account', signInEmail: 'Sign in with email or phone', forgotPassword: 'Forgot password?',
  emailOrPhone: 'Email or phone number', setupPending: 'Pick a handle and accept the terms to finish your account.',
});
Object.assign(ar, {
  continueApple: 'كمّل بأبل', finishSetup: 'كمّل إعداد حسابك', accountSettings: 'إعدادات الحساب',
  createAccountFull: 'اعمل حساب', signInEmail: 'سجّل دخول بالإيميل أو التليفون', forgotPassword: 'نسيت كلمة السر؟',
  emailOrPhone: 'الإيميل أو رقم التليفون', setupPending: 'اختار اسم مستخدم ووافق على الشروط عشان تكمّل حسابك.',
});

// Simulators tab.
Object.assign(en, {
  simulatorsForYou: 'Picked for the courses on your Home tab. Add a course there and its simulators appear here.',
  simulatorsEmpty: 'None of your courses has a simulator yet. Add courses on your Home tab, like Logic Design, Discrete Math, Python, Calculus or Physics, to unlock theirs. Here are a few to start with.',
  simulatorsStarter: 'To get you started',
});
Object.assign(ar, {
  simulatorsForYou: 'مختارة حسب المواد اللي في الصفحة الرئيسية. ضيف مادة هناك وهتلاقي المحاكاة بتاعتها هنا.',
  simulatorsEmpty: 'لسه مفيش محاكاة لموادك. ضيف موادك في الصفحة الرئيسية زي Logic Design أو Discrete Math أو Python أو Calculus أو Physics عشان تفتح بتاعتها. ودي شوية تبدأ بيهم.',
  simulatorsStarter: 'عشان تبدأ',
});
